/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tambah_Anggota.java
 *
 * Created on May 8, 2014, 9:46:13 PM
 */
package Perdagangan;

import Perdagangan.Kontrol.Anggota;
import Perdagangan.Kontrol.Anggota_Kontrol;
import Perdagangan.Kontrol.Barang;
import Perdagangan.Kontrol.Barang_Kontrol;
import Perdagangan.Kontrol.Hutang;
import Perdagangan.Kontrol.Piutang;
import Perdagangan.Kontrol.Transaksi;
import Perdagangan.Kontrol.Transaksi_Kontrol;
import Perdagangan.TabelModel.Tabel_Model_Anggota;
import Perdagangan.TabelModel.Tabel_Model_Barang;
import Perdagangan.TabelModel.Tabel_Model_Transaksi;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author Adhi
 */
public class Per_TransaksiPembelian extends javax.swing.JFrame {

    String file = "../gambar/bg.jpg";

    /**
     * Creates new form Tambah_Anggota
     */
    public Per_TransaksiPembelian() {
        try {
            initComponents();
            this.setLocationRelativeTo(null);

            dialogBarang.setVisible(false);
            dialogBarang.setSize(500, 300);
            dialogBarang.setLocationRelativeTo(null);
            dialogBarang.setTitle("Pencarian Barang");

            dialogPembeli.setVisible(false);
            dialogPembeli.setSize(500, 300);
            dialogPembeli.setLocationRelativeTo(null);
            dialogPembeli.setTitle("Pencarian Pembeli");

            List<Barang> kategoris = Barang_Kontrol.getKoneksi().tampilAllBarang();
            for (Barang k : kategoris) {
                isianBarang.addItem(k.namaBarang);
            }
            updateTabelTransaksi();
            updateTabelBarang();
            updateTabelPembeli();
            updateTabelHutang();
        } catch (Exception ex) {
            Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogBarang = new javax.swing.JDialog();
        panelBarang = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        isianCariBarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dialogPembeli = new javax.swing.JDialog();
        panelBarang1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelPembeli = new javax.swing.JTable();
        isianCariPembeli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        tombolKembali = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        isian_kodeTransaksi = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        tombolTambah = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        tombolBatal = new javax.swing.JButton();
        isianBarang = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        isianJumlah = new javax.swing.JTextField();
        isianSatuan = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        isianTotalPenjualan = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        isianNamaPembeli = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        isianJenisPembayaran = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        isianTanggal = new com.toedter.calendar.JDateChooser();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        jPanel19 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelKodeBarang = new javax.swing.JLabel();
        labelNamaBarang = new javax.swing.JLabel();
        labelJumlahStok = new javax.swing.JLabel();
        labelSatuan = new javax.swing.JLabel();
        labelHargaSatuan = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPiutang = new javax.swing.JTable();

        panelBarang.setBackground(new java.awt.Color(204, 204, 0));
        panelBarang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TABEL BARANG", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelBarang);

        isianCariBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                isianCariBarangKeyReleased(evt);
            }
        });

        jLabel5.setText("Cari");

        javax.swing.GroupLayout panelBarangLayout = new javax.swing.GroupLayout(panelBarang);
        panelBarang.setLayout(panelBarangLayout);
        panelBarangLayout.setHorizontalGroup(
            panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(panelBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(isianCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBarangLayout.setVerticalGroup(
            panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isianCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogBarangLayout = new javax.swing.GroupLayout(dialogBarang.getContentPane());
        dialogBarang.getContentPane().setLayout(dialogBarangLayout);
        dialogBarangLayout.setHorizontalGroup(
            dialogBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogBarangLayout.setVerticalGroup(
            dialogBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelBarang1.setBackground(new java.awt.Color(204, 204, 0));
        panelBarang1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TABEL PEMBELI", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jScrollPane4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane4MouseClicked(evt);
            }
        });

        tabelPembeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPembeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPembeliMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelPembeli);

        isianCariPembeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                isianCariPembeliKeyReleased(evt);
            }
        });

        jLabel6.setText("Cari");

        jButton3.setText("TAMBAH PENJUAL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBarang1Layout = new javax.swing.GroupLayout(panelBarang1);
        panelBarang1.setLayout(panelBarang1Layout);
        panelBarang1Layout.setHorizontalGroup(
            panelBarang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(panelBarang1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(isianCariPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBarang1Layout.setVerticalGroup(
            panelBarang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarang1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBarang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isianCariPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogPembeliLayout = new javax.swing.GroupLayout(dialogPembeli.getContentPane());
        dialogPembeli.getContentPane().setLayout(dialogPembeliLayout);
        dialogPembeliLayout.setHorizontalGroup(
            dialogPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogPembeliLayout.setVerticalGroup(
            dialogPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRANSAKSI SIMPAN & PINJAM");

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TRANSAKSI PEMBELIAN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Times New Roman", 3, 24))); // NOI18N

        jPanel10.setBackground(new java.awt.Color(204, 204, 0));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tombolKembali.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tombolKembali.setText("KEMBALI");
        tombolKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tombolKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tombolKembali, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(204, 204, 0));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PENJUALAN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel20.setText("Kode Transaksi");

        jLabel52.setText("Pembelian Barang");

        jLabel53.setText("Jumlah ");

        tombolTambah.setText("PROSES");
        tombolTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahActionPerformed(evt);
            }
        });

        tombolHapus.setText("HAPUS");
        tombolHapus.setEnabled(false);
        tombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusActionPerformed(evt);
            }
        });

        tombolBatal.setText("BATAL");
        tombolBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolBatalActionPerformed(evt);
            }
        });

        isianBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isianBarangActionPerformed(evt);
            }
        });

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        isianSatuan.setText("<<satuan>>");

        jLabel55.setText("Total Harga");

        jLabel56.setText("Nama Penjual");

        isianNamaPembeli.setEditable(false);

        jLabel57.setText("Jenis Pembayaran");

        isianJenisPembayaran.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TUNAI", "HUTANG" }));

        jButton2.setText("Cari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                            .addComponent(tombolTambah)
                            .addGap(34, 34, 34)
                            .addComponent(tombolHapus)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tombolBatal))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel52)
                                .addComponent(jLabel53)
                                .addComponent(jLabel20)
                                .addComponent(jLabel55)
                                .addComponent(jLabel56))
                            .addGap(20, 20, 20)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel13Layout.createSequentialGroup()
                                    .addComponent(isianJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(isianSatuan))
                                .addComponent(isianTotalPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(isian_kodeTransaksi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(isianTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(isianBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(isianNamaPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel57)
                                .addGap(18, 18, 18)
                                .addComponent(isianJenisPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(isian_kodeTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(isianTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(isianBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isianJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isianSatuan)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel53)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(isianTotalPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(isianNamaPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(isianJenisPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel18.setBackground(new java.awt.Color(204, 204, 0));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TABEL TRANSAKSI", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTransaksi);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel19.setBackground(new java.awt.Color(204, 204, 0));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMASI STOK", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel1.setText("KODE BARANG");

        jLabel2.setText("NAMA BARANG");

        jLabel3.setText("JUMLAH STOK");

        jLabel4.setText("HARGA SATUAN");

        labelKodeBarang.setText("<<ISI>>");

        labelNamaBarang.setText("<<ISI>>");

        labelJumlahStok.setText("<<ISI>>");

        labelSatuan.setText("<<ISI>>");

        labelHargaSatuan.setText("<<ISI>>");

        jLabel10.setText("Rp");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(labelKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(labelJumlahStok, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelKodeBarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelNamaBarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelJumlahStok)
                    .addComponent(labelSatuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelHargaSatuan)
                    .addComponent(jLabel10))
                .addGap(29, 29, 29))
        );

        jPanel20.setBackground(new java.awt.Color(204, 204, 0));
        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TABEL HUTANG", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        tabelPiutang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPiutang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPiutangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPiutang);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKembaliActionPerformed
        // TODO add your handling code here:
        new Perdagangan_Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolKembaliActionPerformed

    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMouseClicked
        int row1 = tabelTransaksi.getSelectedRow();
        isian_kodeTransaksi.setText(tabelTransaksi.getValueAt(row1, 0).toString());//0 kolom pertama
        isianTanggal.setDateFormatString(tabelTransaksi.getValueAt(row1, 1).toString());//blm
        isianBarang.setSelectedItem(tabelTransaksi.getValueAt(row1, 2).toString());//blm
        isianJumlah.setText(file);//blm
        isianTotalPenjualan.setText(file);//blm
        isianNamaPembeli.setText(file);//blm
        isianJenisPembayaran.setSelectedItem(evt);//blm
        tombolHapus.setEnabled(true);
        isian_kodeTransaksi.setEditable(false);

        //isian buat label
        try {
            Barang brg = Barang_Kontrol.getKoneksi().tampilBarang(isianBarang.getSelectedItem().toString());
            labelKodeBarang.setText(brg.kodeBarang);
            labelNamaBarang.setText(brg.namaBarang);
            labelSatuan.setText(brg.satuanBarang);
            labelHargaSatuan.setText(Long.toString(brg.hargaSatuan));
            labelJumlahStok.setText(Integer.toString(brg.jumlahStok));
        } catch (SQLException ex) {
            Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabelTransaksiMouseClicked

    private void tombolBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBatalActionPerformed
        bersihkan();
    }//GEN-LAST:event_tombolBatalActionPerformed

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        int jwb = JOptionPane.showConfirmDialog(rootPane, "Yakin Hapus?");//O yes, 1 No, 2 Cancel
        if (jwb == 0) {
            try {
                Anggota agt = new Anggota();
                agt.noAnggota = isian_kodeTransaksi.getText();
                Perdagangan.Kontrol.Anggota_Kontrol.getKoneksi().deleteAnggota(agt.noAnggota);
                JOptionPane.showMessageDialog(rootPane, "Penghapusan Member Sukses");
                updateTabelTransaksi();
                bersihkan();
            } catch (SQLException ex) {
                Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void tombolTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTambahActionPerformed
        try {
            Barang cek = Barang_Kontrol.getKoneksi().tampilBarang(isianBarang.getSelectedItem().toString());
            if (cek.jumlahStok - Integer.parseInt(isianJumlah.getText()) < 0) {
                JOptionPane.showMessageDialog(rootPane, "Stok Barang " + cek.namaBarang + " Tidak mencukupi");
            } else {
                Transaksi t = new Transaksi();
                t.kodeTransaksi = isian_kodeTransaksi.getText();
                t.idBarang = isianBarang.getSelectedItem().toString();
                t.jumlah = Integer.parseInt(isianJumlah.getText());
                t.totalPenjualan = Long.parseLong(isianTotalPenjualan.getText());
                t.idPembeli = isianNamaPembeli.getText();
                t.jenisPembayaran = isianJenisPembayaran.getSelectedItem().toString();
                Date tanggal = isianTanggal.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String tgl = sdf.format(tanggal);
                t.tanggal = tgl;
                if (t.jenisPembayaran.equals("TUNAI")) {
                    t.status = "LUNAS";
                } else {
                    t.status = "HUTANG";
                    Hutang htg = new Hutang();//untuk tabel piutang
                    htg.kodeTransaksi = t.kodeTransaksi;
                    htg.tanggal = t.tanggal;
                    Transaksi_Kontrol.getKoneksi().insertHutang(htg);
                }
                
                try {
                    Transaksi_Kontrol.getKoneksi().insertBarang(t);
                    JOptionPane.showMessageDialog(rootPane, "Transaksi berhasil ditambahkan");
                    updateTabelTransaksi();
                    updateTabelHutang();
                    //disini tempat pengurangan stok barang
                    cek.jumlahStok = cek.jumlahStok + t.jumlah;
                    updateStokBarang(cek);
                } catch (SQLException ex) {
                    Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tombolTambahActionPerformed

    private void tabelPiutangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPiutangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelPiutangMouseClicked

    private void isianBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isianBarangActionPerformed
        try {
            Barang brg = Barang_Kontrol.getKoneksi().tampilBarang(isianBarang.getSelectedItem().toString());
            labelKodeBarang.setText(brg.kodeBarang);
            labelNamaBarang.setText(brg.namaBarang);
            labelSatuan.setText(brg.satuanBarang);
            isianSatuan.setText(brg.satuanBarang);
            labelHargaSatuan.setText(Long.toString(brg.hargaSatuan));
            labelJumlahStok.setText(Integer.toString(brg.jumlahStok));
        } catch (SQLException ex) {
            Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_isianBarangActionPerformed

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        int row1 = tabelBarang.getSelectedRow();
        isianBarang.setSelectedItem(tabelBarang.getValueAt(row1, 1).toString());//0 kolom pertama
        dialogBarang.setVisible(false);
    }//GEN-LAST:event_tabelBarangMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dialogBarang.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelPembeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPembeliMouseClicked
        int row1 = tabelPembeli.getSelectedRow();
        isianNamaPembeli.setText(tabelPembeli.getValueAt(row1, 1).toString());//0 kolom pertama
        dialogPembeli.setVisible(false);
    }//GEN-LAST:event_tabelPembeliMouseClicked

    private void isianCariBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isianCariBarangKeyReleased
        String cari = isianCariBarang.getText();
        try {
            cariBarang(cari);
        } catch (SQLException ex) {
            Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_isianCariBarangKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dialogPembeli.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Per_Anggota per = new Per_Anggota("beck");
        per.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void isianCariPembeliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isianCariPembeliKeyReleased
        String cari = isianCariPembeli.getText();

        try {
            cariPembeli(cari);
        } catch (Exception ex) {
            Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_isianCariPembeliKeyReleased

    private void jScrollPane4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane4MouseClicked
//    public static String bulan(int b) {
//        String bb = "";
//        if (b == 1) {
//            bb = "JAN";
//        } else if (b == 2) {
//            bb = "FEB";
//        } else if (b == 3) {
//            bb = "MAR";
//        } else if (b == 4) {
//            bb = "APR";
//        } else if (b == 5) {
//            bb = "MAY";
//        } else if (b == 6) {
//            bb = "JUN";
//        } else if (b == 7) {
//            bb = "JUL";
//        } else if (b == 8) {
//            bb = "AUG";
//        } else if (b == 9) {
//            bb = "SEP";
//        } else if (b == 10) {
//            bb = "OKT";
//        } else if (b == 11) {
//            bb = "NOV";
//        } else if (b == 12) {
//            bb = "DEC";
//        }
//        return bb;
//    }

    public void tampilSimpanan(String nik) throws Exception {
//        List<Simpanan> a = Kontrol_Simpanan.getKoneksi().getAllSimpanan(nik);
//        Tabel_Model_Daftar_Simpanan model = new Tabel_Model_Daftar_Simpanan(a);
//        tabel_Daftar_Simpanan.setModel(model);
    }

    public void tampilPinjaman(String nik) throws Exception {
//        List<Pinjaman> a = Kontrol_Pinjaman.getKoneksi().getAllPinjaman(nik);
//        Tabel_Model_Daftar_Pinjaman model = new Tabel_Model_Daftar_Pinjaman(a);
//        tabel_Daftar_Pinjaman.setModel(model);
    }

    public void STATUSPinjaman(String nik) throws Exception {
//        List<Pinjaman> a = Kontrol_Pinjaman.getKoneksi().getAllPinjaman(nik);
//        double p = 0;
//        for (int i = 0; i < a.size(); i++) {
//            p += (a.get(i).getSaldo_Pokok_pinjaman() + a.get(i).getSaldo_Bunga());
//        }
//        if (p > 0) {
//            label_status_pinjam.setText(": Pinjam");
//        }
    }

    public void updateTabelHutang() throws Exception {
        List<Transaksi> a = Transaksi_Kontrol.getKoneksi().tampilHutang();
        Tabel_Model_Transaksi model = new Tabel_Model_Transaksi(a);
        tabelPiutang.setModel(model);
    }
    
    public void updateTabelTransaksi() throws Exception {
        List<Transaksi> a = Perdagangan.Kontrol.Transaksi_Kontrol.getKoneksi().tampilAllTransaksi();
        Tabel_Model_Transaksi model = new Tabel_Model_Transaksi(a);
        tabelTransaksi.setModel(model);
    }

    public void updateTabelBarang() throws Exception {
        List<Barang> a = Perdagangan.Kontrol.Barang_Kontrol.getKoneksi().tampilAllBarang();
        Tabel_Model_Barang model = new Tabel_Model_Barang(a);
        tabelBarang.setModel(model);
    }

    public void updateTabelPembeli() throws Exception {
        List<Anggota> a = Perdagangan.Kontrol.Anggota_Kontrol.getKoneksi().tampilAllAnggota();
        Tabel_Model_Anggota model = new Tabel_Model_Anggota(a);
        tabelPembeli.setModel(model);
    }

    private void cariBarang(String cari) throws SQLException {
        List<Barang> a = Barang_Kontrol.getKoneksi().cariBarang(cari);
        Tabel_Model_Barang model = new Tabel_Model_Barang(a);
        tabelBarang.setModel(model);
    }

    public void cariPembeli(String cari) throws Exception {
        List<Anggota> a = Anggota_Kontrol.getKoneksi().cariAnggota(cari);
        Tabel_Model_Anggota model = new Tabel_Model_Anggota(a);
        tabelPembeli.setModel(model);
    }

    public void updateStokBarang(Barang b) throws Exception {
        b.hrgBarang = b.jumlahStok * b.hargaSatuan;
        Barang_Kontrol.getKoneksi().updateBarang(b);
        labelKodeBarang.setText(b.kodeBarang);
        labelNamaBarang.setText(b.namaBarang);
        labelSatuan.setText(b.satuanBarang);
        isianSatuan.setText(b.satuanBarang);
        labelHargaSatuan.setText(Long.toString(b.hargaSatuan));
        labelJumlahStok.setText(Integer.toString(b.jumlahStok));
    }

    public void bersihkan() {
        isian_kodeTransaksi.setText("");
        isianTanggal.setDateFormatString("");
        isianJumlah.setText("");
        isianTotalPenjualan.setText("");
        isianNamaPembeli.setText("");
        isianJenisPembayaran.setSelectedItem("TUNAI");
        tombolHapus.setEnabled(false);
        isian_kodeTransaksi.setEditable(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
            java.awt.EventQueue.invokeLater(new Runnable() {

                public void run() {
                    new Per_TransaksiPembelian().setVisible(true);
                }
            });
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dialogBarang;
    private javax.swing.JDialog dialogPembeli;
    private javax.swing.JComboBox isianBarang;
    private javax.swing.JTextField isianCariBarang;
    private javax.swing.JTextField isianCariPembeli;
    private javax.swing.JComboBox isianJenisPembayaran;
    private javax.swing.JTextField isianJumlah;
    private javax.swing.JTextField isianNamaPembeli;
    private javax.swing.JLabel isianSatuan;
    private com.toedter.calendar.JDateChooser isianTanggal;
    private javax.swing.JTextField isianTotalPenjualan;
    private javax.swing.JTextField isian_kodeTransaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelHargaSatuan;
    private javax.swing.JLabel labelJumlahStok;
    private javax.swing.JLabel labelKodeBarang;
    private javax.swing.JLabel labelNamaBarang;
    private javax.swing.JLabel labelSatuan;
    private javax.swing.JPanel panelBarang;
    private javax.swing.JPanel panelBarang1;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JTable tabelPembeli;
    private javax.swing.JTable tabelPiutang;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JButton tombolBatal;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolKembali;
    private javax.swing.JButton tombolTambah;
    // End of variables declaration//GEN-END:variables
}
