/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tambah_Anggota.java
 *
 * Created on May 8, 2014, 9:46:13 PM
 */
package Perdagangan;

import Perdagangan.Kontrol.Anggota;
import Perdagangan.Kontrol.Anggota_Kontrol;
import Perdagangan.Kontrol.Barang;
import Perdagangan.Kontrol.Barang_Kontrol;
import Perdagangan.Kontrol.Transaksi;
import Perdagangan.Kontrol.Transaksi_Kontrol;
import Perdagangan.TabelModel.Tabel_Model_Anggota;
import Perdagangan.TabelModel.Tabel_Model_Barang;
import Perdagangan.TabelModel.Tabel_Model_Transaksi;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author Adhi
 */
public class Per_TransaksiPembelian extends javax.swing.JFrame {

    String file = "../gambar/bg.jpg";

    /**
     * Creates new form Tambah_Anggota
     */
    public Per_TransaksiPembelian() {
        try {
            initComponents();
            this.getRootPane().setDefaultButton(tombolTambah);//biar bisa enter
            this.setLocationRelativeTo(null);

            GregorianCalendar gc = new GregorianCalendar();
            isian_tanggal.setDate(gc.getTime());
            isianNamaBarang.requestFocus();
            buatIDTransaksi();
            isai.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        tombolKembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        isian_idAgt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        isian_alamatAgt = new javax.swing.JTextArea();
        isian_namaAgt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        isian_noTelpAgt = new javax.swing.JTextField();
        buttonProses = new javax.swing.JButton();
        isai = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        isian_kodeTransaksi = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        tombolTambah = new javax.swing.JButton();
        isianJumlah = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        isianTotalPenjualan = new javax.swing.JTextField();
        isianNamaBarang = new javax.swing.JTextField();
        isianHargaSatuan = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        isian_tanggal = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        isianTotalPembayaran = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboPembayaran = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRANSAKSI SIMPAN & PINJAM");

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TRANSAKSI PEMBELIAN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Times New Roman", 3, 24))); // NOI18N

        jPanel10.setBackground(new java.awt.Color(204, 204, 0));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tombolKembali.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tombolKembali.setText("KEMBALI");
        tombolKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKembaliActionPerformed(evt);
            }
        });

        jLabel4.setText("No Identitas");

        isian_idAgt.setEditable(false);
        isian_idAgt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                isian_idAgtKeyReleased(evt);
            }
        });

        jLabel5.setText("Nama");

        jLabel6.setText("Alamat");

        isian_alamatAgt.setEditable(false);
        isian_alamatAgt.setColumns(20);
        isian_alamatAgt.setRows(5);
        jScrollPane3.setViewportView(isian_alamatAgt);

        isian_namaAgt.setEditable(false);

        jLabel8.setText("No Telp");

        isian_noTelpAgt.setEditable(false);

        buttonProses.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonProses.setText("PROSES");
        buttonProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProsesActionPerformed(evt);
            }
        });

        isai.setText("<<>>");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(41, 41, 41)
                        .addComponent(isian_noTelpAgt, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(isian_idAgt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(isai))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(isian_namaAgt)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonProses, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(tombolKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(isian_idAgt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(isian_namaAgt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isian_noTelpAgt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tombolKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonProses, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(204, 204, 0));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PEMBELIAN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel20.setText("Kode Transaksi");

        isian_kodeTransaksi.setEditable(false);

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel52.setText("NAMA BARANG");

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel53.setText("JUMLAH");

        tombolTambah.setText("TAMBAH");
        tombolTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahActionPerformed(evt);
            }
        });

        isianJumlah.setText("0");
        isianJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                isianJumlahKeyReleased(evt);
            }
        });

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel55.setText("TOTAL HARGA");

        isianTotalPenjualan.setEditable(false);
        isianTotalPenjualan.setText("0");

        isianNamaBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                isianNamaBarangKeyReleased(evt);
            }
        });

        isianHargaSatuan.setText("0");
        isianHargaSatuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                isianHargaSatuanKeyReleased(evt);
            }
        });

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel54.setText("HARGA SATUAN");

        isian_tanggal.setDateFormatString("dd-MM-yyyy");

        jLabel1.setText("TANGGAL");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(isian_kodeTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(isian_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(isianNamaBarang))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(isianHargaSatuan)
                            .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(isianJumlah)
                            .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(isianTotalPenjualan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tombolTambah)
                        .addGap(10, 10, 10))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(isian_kodeTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(isian_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(jLabel53)
                    .addComponent(jLabel55)
                    .addComponent(jLabel54))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isianNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isianJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isianTotalPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isianHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(204, 204, 0));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TABEL TRANSAKSI", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTransaksi);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PEMBAYARAN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Rp");

        isianTotalPembayaran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        isianTotalPembayaran.setText("0");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("TOTAL YANG HARUS DIBAYAR");

        comboPembayaran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboPembayaran.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TUNAI", "HUTANG" }));
        comboPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPembayaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboPembayaran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isianTotalPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 440, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isianTotalPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKembaliActionPerformed
        // TODO add your handling code here:
        new Perdagangan_Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolKembaliActionPerformed

    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMouseClicked
//        int row1 = tabelTransaksi.getSelectedRow();
//        isian_kodeTransaksi.setText(tabelTransaksi.getValueAt(row1, 0).toString());//0 kolom pertama
//        isianTanggal.setDateFormatString(tabelTransaksi.getValueAt(row1, 1).toString());//blm
//        isianBarang.setSelectedItem(tabelTransaksi.getValueAt(row1, 2).toString());//blm
//        isianJumlah.setText(file);//blm
//        isianTotalPenjualan.setText(file);//blm
//        isianNamaPembeli.setText(file);//blm
//        isianJenisPembayaran.setSelectedItem(evt);//blm
//        tombolHapus.setEnabled(true);
//        isian_kodeTransaksi.setEditable(false);
//
//        //isian buat label
//        try {
//            Barang brg = Barang_Kontrol.getKoneksi().tampilBarang(isianBarang.getSelectedItem().toString());
//            labelKodeBarang.setText(brg.kodeBarang);
//            labelNamaBarang.setText(brg.namaBarang);
//            labelSatuan.setText(brg.satuanBarang);
//            labelHargaSatuan.setText(Long.toString(brg.hargaSatuan));
//            labelJumlahStok.setText(Integer.toString(brg.jumlahStok));
//        } catch (SQLException ex) {
//            Logger.getLogger(Per_TransaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_tabelTransaksiMouseClicked

    private void tombolTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTambahActionPerformed
        Barang brg = new Barang();
        brg.namaBarang = isianNamaBarang.getText();

        Transaksi trans = new Transaksi();
        trans.kodeTransaksi = isian_kodeTransaksi.getText();
        trans.idBarang = brg.namaBarang;
        trans.jumlah = Integer.parseInt(isianJumlah.getText());
        trans.totalPenjualan = Long.parseLong(isianTotalPenjualan.getText());
        trans.idPembeli = "-";
        trans.jenisPembayaran = "-";
        trans.status = "BLM";

        Date tanggal = isian_tanggal.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tgl = sdf.format(tanggal);
        trans.tanggal = tgl;
        try {
            Transaksi_Kontrol.getKoneksi().insertTransaksi(trans);
            updateTabelTransaksi();
            bersihkan();
            updateTotalBayar();
        } catch (SQLException ex) {
            Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
        isianNamaBarang.requestFocus();
    }//GEN-LAST:event_tombolTambahActionPerformed

    private void isianJumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isianJumlahKeyReleased
        if (isianJumlah.getText().equals("")) {
            isianTotalPenjualan.setText("0");
        } else {
            long total = Long.parseLong(isianHargaSatuan.getText()) * Long.parseLong(isianJumlah.getText());
            isianTotalPenjualan.setText(Long.toString(total));
        }
    }//GEN-LAST:event_isianJumlahKeyReleased

    private void isianNamaBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isianNamaBarangKeyReleased
//        try {
//            Barang brg = Barang_Kontrol.getKoneksi().tampilBarang(isianNamaBarang.getText());
//            isianHargaSatuan.setText(Long.toString(brg.hargaSatuan));
//        } catch (SQLException ex) {
//            Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_isianNamaBarangKeyReleased

    private void buttonProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProsesActionPerformed
        if (comboPembayaran.getSelectedItem().toString().equals("TUNAI")) {
            try {
                Transaksi trans = new Transaksi();
                trans.kodeTransaksi = isian_kodeTransaksi.getText();
                trans.jenisPembayaran = comboPembayaran.getSelectedItem().toString();
                trans.status = "BELI_LUNAS";
                Transaksi_Kontrol.getKoneksi().updateTransaksi(trans);
                JOptionPane.showMessageDialog(rootPane, "Transaksi Selesai");
                buatIDTransaksi();
                bersihkan();
            } catch (SQLException ex) {
                Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            if (isian_idAgt.getText().equals("") && isian_namaAgt.getText().equals("")
                    && isian_alamatAgt.getText().equals("") && isian_noTelpAgt.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Harap Mengisi form yang masih kosong");
            } else {
                if (isai.getText().equals("ada")) {
                    try {
                        Anggota agt = new Anggota();
                        agt.noIdentitas = isian_idAgt.getText();
                        agt.namaAnggota = isian_namaAgt.getText();
                        agt.alamat = isian_alamatAgt.getText();
                        agt.noTelp = isian_noTelpAgt.getText();
                        Anggota_Kontrol.getKoneksi().updateAnggota(agt);
                        
                        Transaksi trans = new Transaksi();
                        trans.kodeTransaksi = isian_kodeTransaksi.getText();
                        trans.jenisPembayaran = "HUTANG";
                        trans.idPembeli = agt.noIdentitas;
                        trans.status = "BLM";
                        Transaksi_Kontrol.getKoneksi().updateTransaksi2(trans);
                        JOptionPane.showMessageDialog(rootPane, "Transaksi Selesai");
                        buatIDTransaksi();
                        bersihkan();
                    } catch (SQLException ex) {
                        Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    try {
                        Anggota agt = new Anggota();
                        agt.noIdentitas = isian_idAgt.getText();
                        agt.namaAnggota = isian_namaAgt.getText();
                        agt.alamat = isian_alamatAgt.getText();
                        agt.noTelp = isian_noTelpAgt.getText();
                        Anggota_Kontrol.getKoneksi().insertAnggota(agt);
                        
                        Transaksi trans = new Transaksi();
                        trans.kodeTransaksi = isian_kodeTransaksi.getText();
                        trans.jenisPembayaran = "HUTANG";
                        trans.idPembeli = agt.noIdentitas;
                        trans.status = "BLM";
                        Transaksi_Kontrol.getKoneksi().updateTransaksi2(trans);
                        JOptionPane.showMessageDialog(rootPane, "Transaksi Selesai");
                        buatIDTransaksi();
                        bersihkan();
                    } catch (SQLException ex) {
                        Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_buttonProsesActionPerformed

    private void comboPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPembayaranActionPerformed
        if (comboPembayaran.getSelectedItem().toString().equals("TUNAI")) {
            isian_idAgt.setEditable(false);
            isian_namaAgt.setEditable(false);
            isian_alamatAgt.setEditable(false);
            isian_noTelpAgt.setEditable(false);
        } else {
            isian_idAgt.setEditable(true);
            isian_namaAgt.setEditable(true);
            isian_alamatAgt.setEditable(true);
            isian_noTelpAgt.setEditable(true);
        }
    }//GEN-LAST:event_comboPembayaranActionPerformed

    private void isian_idAgtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isian_idAgtKeyReleased
        try {
            Anggota agt = Anggota_Kontrol.getKoneksi().cariAnggota(isian_idAgt.getText());
            if (agt != null) {
                isian_namaAgt.setText(agt.namaAnggota);
                isian_alamatAgt.setText(agt.alamat);
                isian_noTelpAgt.setText(agt.noTelp);
                isai.setText("ada");
            } else {
                isai.setText("tdk");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_isian_idAgtKeyReleased

    private void isianHargaSatuanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isianHargaSatuanKeyReleased
        if (isianHargaSatuan.getText().equals("")) {
            isianTotalPenjualan.setText("0");
        } else {
            long total = Long.parseLong(isianHargaSatuan.getText()) * Long.parseLong(isianJumlah.getText());
            isianTotalPenjualan.setText(Long.toString(total));
        }
    }//GEN-LAST:event_isianHargaSatuanKeyReleased

    public void updateTabelTransaksi() throws Exception {
        List<Transaksi> a = Perdagangan.Kontrol.Transaksi_Kontrol.getKoneksi().tampilAllTransaksi(isian_kodeTransaksi.getText());
        Tabel_Model_Transaksi model = new Tabel_Model_Transaksi(a);
        tabelTransaksi.setModel(model);
    }

    public void updateStokBarang(Barang b) throws Exception {
//        b.hrgBarang = b.jumlahStok * b.hargaSatuan;
//        Barang_Kontrol.getKoneksi().updateBarang(b);
//        labelKodeBarang.setText(b.kodeBarang);
//        labelNamaBarang.setText(b.namaBarang);
//        labelSatuan.setText(b.satuanBarang);
//        isianSatuan.setText(b.satuanBarang);
//        labelHargaSatuan.setText(Long.toString(b.hargaSatuan));
//        labelJumlahStok.setText(Integer.toString(b.jumlahStok));
    }

    public void bersihkan() {
        isianNamaBarang.setText("");
        isianHargaSatuan.setText("0");
        isianJumlah.setText("0");
        isianTotalPenjualan.setText("0");
        isianTotalPembayaran.setText("0");
    }

    public void buatIDTransaksi() {
        String kode = null;
        try {
            kode = Transaksi_Kontrol.getKoneksi().generateID();
            isian_kodeTransaksi.setText(kode);
            updateTabelTransaksi();
        } catch (SQLException ex) {
            Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
            java.awt.EventQueue.invokeLater(new Runnable() {

                public void run() {
                    new Per_TransaksiPembelian().setVisible(true);
                }
            });
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonProses;
    private javax.swing.JComboBox comboPembayaran;
    private javax.swing.JLabel isai;
    private javax.swing.JTextField isianHargaSatuan;
    private javax.swing.JTextField isianJumlah;
    private javax.swing.JTextField isianNamaBarang;
    private javax.swing.JLabel isianTotalPembayaran;
    private javax.swing.JTextField isianTotalPenjualan;
    private javax.swing.JTextArea isian_alamatAgt;
    private javax.swing.JTextField isian_idAgt;
    private javax.swing.JTextField isian_kodeTransaksi;
    private javax.swing.JTextField isian_namaAgt;
    private javax.swing.JTextField isian_noTelpAgt;
    private com.toedter.calendar.JDateChooser isian_tanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JButton tombolKembali;
    private javax.swing.JButton tombolTambah;
    // End of variables declaration//GEN-END:variables

    private void updateTotalBayar() {
        try {
            String temp = Transaksi_Kontrol.getKoneksi().tampilHarga(isian_kodeTransaksi.getText());
            isianTotalPembayaran.setText(temp);
        } catch (SQLException ex) {
            Logger.getLogger(Per_TransaksiPembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
