/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tambah_Anggota.java
 *
 * Created on May 8, 2014, 9:46:13 PM
 */
package bumdes;

import Kontrol.Kontrol_Anggota;
import Kontrol.Kontrol_Pinjaman;
import Kontrol.Kontrol_Simpanan;
import Tabel_Model.Anggota;
import Tabel_Model.Pinjaman;
import Tabel_Model.Simpanan;
import Tabel_list_Model.Tabel_Model_Cari_Anggota;
import Tabel_list_Model.Tabel_Model_Daftar_Pinjaman;
import Tabel_list_Model.Tabel_Model_Daftar_Simpanan;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author Rafael Aweng
 */
public class AirBersih extends javax.swing.JFrame {

    String file = "../gambar/bg.jpg";

    /** Creates new form Tambah_Anggota */
    public AirBersih() {
        initComponents();
        this.setLocationRelativeTo(null);

        air_baku.setVisible(false);
        air_baku.setSize(500, 300);
        air_baku.setLocationRelativeTo(null);
        air_baku.setTitle("AIR BAKU");

        air_produksi.setVisible(false);
        air_produksi.setSize(500, 300);
        air_produksi.setLocationRelativeTo(null);
        air_produksi.setTitle("AIR PRODUKSI");

        bahan_kimia.setVisible(false);
        bahan_kimia.setSize(550, 300);
        bahan_kimia.setLocationRelativeTo(null);
        bahan_kimia.setTitle("BAHAN KIMIA");

        pemakaian_listrik.setVisible(false);
        pemakaian_listrik.setSize(780, 335);
        pemakaian_listrik.setLocationRelativeTo(null);
        pemakaian_listrik.setTitle("PEMAKAIAN LISTRIK");

        bahan_bakar.setVisible(false);
        bahan_bakar.setSize(430, 470);
        bahan_bakar.setLocationRelativeTo(null);
        bahan_bakar.setTitle("BAHAN BAKAR");
        
        data_pelanggan.setVisible(false);
        data_pelanggan.setSize(500, 300);
        data_pelanggan.setLocationRelativeTo(null);
        data_pelanggan.setTitle("DATA PELANGGAN");
        
        pemakaian_air.setVisible(false);
        pemakaian_air.setSize(500, 300);
        pemakaian_air.setLocationRelativeTo(null);
        pemakaian_air.setTitle("PEMAKAIAN AIR");
        
        pemompaan_distribusi.setVisible(false);
        pemompaan_distribusi.setSize(500, 300);
        pemompaan_distribusi.setLocationRelativeTo(null);
        pemompaan_distribusi.setTitle("PEMOMPAAN DISTRIBUSI");
        
        pencucian_pipa.setVisible(false);
        pencucian_pipa.setSize(500, 300);
        pencucian_pipa.setLocationRelativeTo(null);
        pencucian_pipa.setTitle("PENCUCIAN PIPA");
        
        biaya_lab.setVisible(false);
        biaya_lab.setSize(500, 300);
        biaya_lab.setLocationRelativeTo(null);
        biaya_lab.setTitle("BIAYA LAB");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        air_baku = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        tek_nominal_setor_wajib = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tek_nominal_setor_Sukarela = new javax.swing.JTextField();
        air_produksi = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        tek_nominal_tarik = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        tek_nominal_tarik1 = new javax.swing.JTextField();
        bahan_kimia = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tek_jumlah_pinjam = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        tek_jumlah_pinjam1 = new javax.swing.JTextField();
        pemakaian_listrik = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        label_tgl_angsur = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        bahan_bakar = new javax.swing.JDialog();
        jPanel12 = new javax.swing.JPanel();
        tek_cari_anggota = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_cari_anggota = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        data_pelanggan = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        tek_nominal_setor_wajib1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tgl_setoran1 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tek_nominal_setor_Sukarela1 = new javax.swing.JTextField();
        pemakaian_air = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        tek_nominal_setor_wajib2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tgl_setoran2 = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        jButton24 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        tek_nominal_setor_Sukarela2 = new javax.swing.JTextField();
        pemompaan_distribusi = new javax.swing.JDialog();
        jPanel14 = new javax.swing.JPanel();
        tek_nominal_setor_wajib3 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        tgl_setoran3 = new com.toedter.calendar.JDateChooser();
        jLabel41 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        tek_nominal_setor_Sukarela3 = new javax.swing.JTextField();
        pencucian_pipa = new javax.swing.JDialog();
        jPanel15 = new javax.swing.JPanel();
        tek_nominal_setor_wajib4 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        tgl_setoran4 = new com.toedter.calendar.JDateChooser();
        jLabel45 = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        tek_nominal_setor_Sukarela4 = new javax.swing.JTextField();
        biaya_lab = new javax.swing.JDialog();
        jPanel16 = new javax.swing.JPanel();
        tek_nominal_setor_wajib5 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        tgl_setoran5 = new com.toedter.calendar.JDateChooser();
        jLabel49 = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        tek_nominal_setor_Sukarela5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(204, 204, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tek_nominal_setor_wajib.setFont(new java.awt.Font("Times New Roman", 0, 14));
        tek_nominal_setor_wajib.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tek_nominal_setor_wajib.setText("0");
        jPanel3.add(tek_nominal_setor_wajib, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 170, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Debit Harian");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 70, 150, 20));

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton5.setText("Batal");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("DEBIT HARIAN");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 430, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Kapasitas Pompa");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 110, 150, 17));

        tek_nominal_setor_Sukarela.setFont(new java.awt.Font("Times New Roman", 0, 14));
        tek_nominal_setor_Sukarela.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tek_nominal_setor_Sukarela.setText("0");
        jPanel3.add(tek_nominal_setor_Sukarela, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 170, 30));

        javax.swing.GroupLayout air_bakuLayout = new javax.swing.GroupLayout(air_baku.getContentPane());
        air_baku.getContentPane().setLayout(air_bakuLayout);
        air_bakuLayout.setHorizontalGroup(
            air_bakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
            .addGroup(air_bakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
        );
        air_bakuLayout.setVerticalGroup(
            air_bakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
            .addGroup(air_bakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tek_nominal_tarik.setFont(new java.awt.Font("Times New Roman", 0, 14));
        tek_nominal_tarik.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tek_nominal_tarik.setText("0");
        jPanel4.add(tek_nominal_tarik, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 150, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Jumlah Debit Air diproduksi");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 77, 170, 20));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Harga satuan");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 140, 20));

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton6.setText("Batal");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton7.setText("Simpan");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("AIR PRODUKSI");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 460, 20));

        tek_nominal_tarik1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        tek_nominal_tarik1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tek_nominal_tarik1.setText("0");
        jPanel4.add(tek_nominal_tarik1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 150, 30));

        javax.swing.GroupLayout air_produksiLayout = new javax.swing.GroupLayout(air_produksi.getContentPane());
        air_produksi.getContentPane().setLayout(air_produksiLayout);
        air_produksiLayout.setHorizontalGroup(
            air_produksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
            .addGroup(air_produksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 412, Short.MAX_VALUE))
        );
        air_produksiLayout.setVerticalGroup(
            air_produksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
            .addGroup(air_produksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PEMAKAIAN BAHAN KIMIA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel5.setText("BIAYA YG DIKELUARKAN         Rp.");

        tek_jumlah_pinjam.setFont(new java.awt.Font("Times New Roman", 0, 14));
        tek_jumlah_pinjam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tek_jumlah_pinjam.setText("0");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel7.setText("BAHAN KIMIA");

        jButton15.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton15.setText("Simpan");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton14.setText("Batal");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        tek_jumlah_pinjam1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        tek_jumlah_pinjam1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tek_jumlah_pinjam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tek_jumlah_pinjam1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton15)
                        .addGap(18, 18, 18)
                        .addComponent(jButton14))
                    .addComponent(tek_jumlah_pinjam, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(tek_jumlah_pinjam1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tek_jumlah_pinjam1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tek_jumlah_pinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15)
                    .addComponent(jButton14))
                .addContainerGap())
        );

        javax.swing.GroupLayout bahan_kimiaLayout = new javax.swing.GroupLayout(bahan_kimia.getContentPane());
        bahan_kimia.getContentPane().setLayout(bahan_kimiaLayout);
        bahan_kimiaLayout.setHorizontalGroup(
            bahan_kimiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
            .addGroup(bahan_kimiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bahan_kimiaLayout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        bahan_kimiaLayout.setVerticalGroup(
            bahan_kimiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
            .addGroup(bahan_kimiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ANGSURAN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Keterangan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel27.setText("JUMLAH   PINJAMAN");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel28.setText("BUNGA PINJAMAN");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel29.setText("ANGG. POKOK+BUNGA");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel32.setText("JUMLAH   PINJAMAN");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel31.setText("JUMLAH   PINJAMAN");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel30.setText("JUMLAH   PINJAMAN");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("ANGGSURAN KE 1 DARI 12");

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel33.setText("SUDAH DIBAYAR");

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel34.setText("BELUM DIBAYAR");

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel35.setText("JUMLAH   PINJAMAN");

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel36.setText("JUMLAH   PINJAMAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(204, 204, 0));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Anggsuran", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel21.setText("TANGGAL ANGSUR");

        label_tgl_angsur.setFont(new java.awt.Font("Times New Roman", 0, 12));
        label_tgl_angsur.setText("JUMLAH   PINJAMAN");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel8.setText("POKOK       Rp.");

        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel9.setText("DENDA       Rp.");

        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("0");

        jButton17.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton17.setText("Simpan");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton16.setText("Batal");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel26.setText("BUNGA       Rp.");

        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_tgl_angsur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton17)
                        .addGap(31, 31, 31)
                        .addComponent(jButton16))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_tgl_angsur, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17)
                    .addComponent(jButton16))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pemakaian_listrikLayout = new javax.swing.GroupLayout(pemakaian_listrik.getContentPane());
        pemakaian_listrik.getContentPane().setLayout(pemakaian_listrikLayout);
        pemakaian_listrikLayout.setHorizontalGroup(
            pemakaian_listrikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
            .addGroup(pemakaian_listrikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pemakaian_listrikLayout.setVerticalGroup(
            pemakaian_listrikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
            .addGroup(pemakaian_listrikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pemakaian_listrikLayout.createSequentialGroup()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel12.setBackground(new java.awt.Color(204, 204, 0));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pencarian Anggota", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tek_cari_anggota.setFont(new java.awt.Font("Times New Roman", 0, 14));
        tek_cari_anggota.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tek_cari_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tek_cari_anggotaActionPerformed(evt);
            }
        });
        tek_cari_anggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tek_cari_anggotaKeyTyped(evt);
            }
        });
        jPanel12.add(tek_cari_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 300, -1));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("Pencarian");
        jPanel12.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 20));

        tabel_cari_anggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tabel_cari_anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_cari_anggotaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel_cari_anggota);

        jPanel12.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 390, 290));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Perhatian :  Klik dibaris tabel untuk memilih anggota !!");
        jPanel12.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 380, 20));

        javax.swing.GroupLayout bahan_bakarLayout = new javax.swing.GroupLayout(bahan_bakar.getContentPane());
        bahan_bakar.getContentPane().setLayout(bahan_bakarLayout);
        bahan_bakarLayout.setHorizontalGroup(
            bahan_bakarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
            .addGroup(bahan_bakarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))
        );
        bahan_bakarLayout.setVerticalGroup(
            bahan_bakarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
            .addGroup(bahan_bakarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(204, 204, 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tek_nominal_setor_wajib1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        tek_nominal_setor_wajib1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tek_nominal_setor_wajib1.setText("0");
        jPanel9.add(tek_nominal_setor_wajib1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 170, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Simpanan Wajib     Rp.");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 70, 150, 20));

        tgl_setoran1.setDateFormatString("dd-MMM-yyyy");
        tgl_setoran1.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jPanel9.add(tgl_setoran1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 170, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Tanggal");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 140, 150, 20));

        jButton9.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton9.setText("Batal");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Penyetoran  Simpanan");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 430, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Simpanan Sukarela Rp.");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 110, 150, 17));

        tek_nominal_setor_Sukarela1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        tek_nominal_setor_Sukarela1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tek_nominal_setor_Sukarela1.setText("0");
        jPanel9.add(tek_nominal_setor_Sukarela1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 170, 30));

        javax.swing.GroupLayout data_pelangganLayout = new javax.swing.GroupLayout(data_pelanggan.getContentPane());
        data_pelanggan.getContentPane().setLayout(data_pelangganLayout);
        data_pelangganLayout.setHorizontalGroup(
            data_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
            .addGroup(data_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
        );
        data_pelangganLayout.setVerticalGroup(
            data_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
            .addGroup(data_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(204, 204, 0));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tek_nominal_setor_wajib2.setFont(new java.awt.Font("Times New Roman", 0, 14));
        tek_nominal_setor_wajib2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tek_nominal_setor_wajib2.setText("0");
        jPanel11.add(tek_nominal_setor_wajib2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 170, 30));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Simpanan Wajib     Rp.");
        jPanel11.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 70, 150, 20));

        tgl_setoran2.setDateFormatString("dd-MMM-yyyy");
        tgl_setoran2.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jPanel11.add(tgl_setoran2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 170, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Tanggal");
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 140, 150, 20));

        jButton24.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton24.setText("Batal");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton4.setText("Simpan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Penyetoran  Simpanan");
        jPanel11.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 430, -1));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel39.setText("Simpanan Sukarela Rp.");
        jPanel11.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 110, 150, 17));

        tek_nominal_setor_Sukarela2.setFont(new java.awt.Font("Times New Roman", 0, 14));
        tek_nominal_setor_Sukarela2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tek_nominal_setor_Sukarela2.setText("0");
        jPanel11.add(tek_nominal_setor_Sukarela2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 170, 30));

        javax.swing.GroupLayout pemakaian_airLayout = new javax.swing.GroupLayout(pemakaian_air.getContentPane());
        pemakaian_air.getContentPane().setLayout(pemakaian_airLayout);
        pemakaian_airLayout.setHorizontalGroup(
            pemakaian_airLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
            .addGroup(pemakaian_airLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
        );
        pemakaian_airLayout.setVerticalGroup(
            pemakaian_airLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
            .addGroup(pemakaian_airLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(204, 204, 0));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tek_nominal_setor_wajib3.setFont(new java.awt.Font("Times New Roman", 0, 14));
        tek_nominal_setor_wajib3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tek_nominal_setor_wajib3.setText("0");
        jPanel14.add(tek_nominal_setor_wajib3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 170, 30));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel40.setText("Simpanan Wajib     Rp.");
        jPanel14.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 70, 150, 20));

        tgl_setoran3.setDateFormatString("dd-MMM-yyyy");
        tgl_setoran3.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jPanel14.add(tgl_setoran3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 170, -1));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel41.setText("Tanggal");
        jPanel14.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 140, 150, 20));

        jButton25.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton25.setText("Batal");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jButton26.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton26.setText("Simpan");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Penyetoran  Simpanan");
        jPanel14.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 430, -1));

        jLabel43.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel43.setText("Simpanan Sukarela Rp.");
        jPanel14.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 110, 150, 17));

        tek_nominal_setor_Sukarela3.setFont(new java.awt.Font("Times New Roman", 0, 14));
        tek_nominal_setor_Sukarela3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tek_nominal_setor_Sukarela3.setText("0");
        jPanel14.add(tek_nominal_setor_Sukarela3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 170, 30));

        javax.swing.GroupLayout pemompaan_distribusiLayout = new javax.swing.GroupLayout(pemompaan_distribusi.getContentPane());
        pemompaan_distribusi.getContentPane().setLayout(pemompaan_distribusiLayout);
        pemompaan_distribusiLayout.setHorizontalGroup(
            pemompaan_distribusiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
            .addGroup(pemompaan_distribusiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
        );
        pemompaan_distribusiLayout.setVerticalGroup(
            pemompaan_distribusiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
            .addGroup(pemompaan_distribusiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
        );

        jPanel15.setBackground(new java.awt.Color(204, 204, 0));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tek_nominal_setor_wajib4.setFont(new java.awt.Font("Times New Roman", 0, 14));
        tek_nominal_setor_wajib4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tek_nominal_setor_wajib4.setText("0");
        jPanel15.add(tek_nominal_setor_wajib4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 170, 30));

        jLabel44.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel44.setText("Simpanan Wajib     Rp.");
        jPanel15.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 70, 150, 20));

        tgl_setoran4.setDateFormatString("dd-MMM-yyyy");
        tgl_setoran4.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jPanel15.add(tgl_setoran4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 170, -1));

        jLabel45.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel45.setText("Tanggal");
        jPanel15.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 140, 150, 20));

        jButton27.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton27.setText("Batal");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jButton28.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton28.setText("Simpan");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel46.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Penyetoran  Simpanan");
        jPanel15.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 430, -1));

        jLabel47.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel47.setText("Simpanan Sukarela Rp.");
        jPanel15.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 110, 150, 17));

        tek_nominal_setor_Sukarela4.setFont(new java.awt.Font("Times New Roman", 0, 14));
        tek_nominal_setor_Sukarela4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tek_nominal_setor_Sukarela4.setText("0");
        jPanel15.add(tek_nominal_setor_Sukarela4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 170, 30));

        javax.swing.GroupLayout pencucian_pipaLayout = new javax.swing.GroupLayout(pencucian_pipa.getContentPane());
        pencucian_pipa.getContentPane().setLayout(pencucian_pipaLayout);
        pencucian_pipaLayout.setHorizontalGroup(
            pencucian_pipaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
            .addGroup(pencucian_pipaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
        );
        pencucian_pipaLayout.setVerticalGroup(
            pencucian_pipaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
            .addGroup(pencucian_pipaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(204, 204, 0));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tek_nominal_setor_wajib5.setFont(new java.awt.Font("Times New Roman", 0, 14));
        tek_nominal_setor_wajib5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tek_nominal_setor_wajib5.setText("0");
        jPanel16.add(tek_nominal_setor_wajib5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 170, 30));

        jLabel48.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel48.setText("Simpanan Wajib     Rp.");
        jPanel16.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 70, 150, 20));

        tgl_setoran5.setDateFormatString("dd-MMM-yyyy");
        tgl_setoran5.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jPanel16.add(tgl_setoran5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 170, -1));

        jLabel49.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel49.setText("Tanggal");
        jPanel16.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 140, 150, 20));

        jButton29.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton29.setText("Batal");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jButton30.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton30.setText("Simpan");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel50.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Penyetoran  Simpanan");
        jPanel16.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 430, -1));

        jLabel51.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel51.setText("Simpanan Sukarela Rp.");
        jPanel16.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 110, 150, 17));

        tek_nominal_setor_Sukarela5.setFont(new java.awt.Font("Times New Roman", 0, 14));
        tek_nominal_setor_Sukarela5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tek_nominal_setor_Sukarela5.setText("0");
        jPanel16.add(tek_nominal_setor_Sukarela5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 170, 30));

        javax.swing.GroupLayout biaya_labLayout = new javax.swing.GroupLayout(biaya_lab.getContentPane());
        biaya_lab.getContentPane().setLayout(biaya_labLayout);
        biaya_labLayout.setHorizontalGroup(
            biaya_labLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
            .addGroup(biaya_labLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
        );
        biaya_labLayout.setVerticalGroup(
            biaya_labLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
            .addGroup(biaya_labLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRANSAKSI SIMPAN & PINJAM");

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PENGELOLAAN AIR BERSIH", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Times New Roman", 3, 24))); // NOI18N

        jPanel10.setBackground(new java.awt.Color(204, 204, 0));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jButton8.setText("KEMBALI");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton3.setText("CETAK ADMINISTRASI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA HARIAN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(204, 204, 0));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PENGOPERASIAN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jButton10.setText("DEBIT AIR DIPRODUKSI");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("DEBIT AIR BAKU");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("PEMAKAIAN BAHAN BAKAR");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("PEMAKAIAN BAHAN KIMIA");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton18.setText("PEMAKAIAN LISTRIK");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("BIAYA LABORATORIUM");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("DATA PELANGGAN");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setText("PENCATATAN PEMAKAIAN AIR");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setText("PEMOMPAAN DISTRIBUSI");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setText("PENCUCIAN PIPA");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jButton18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jButton20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        air_baku.setVisible(false);
        bersih_layar_setor();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        pemakaian_listrik.setVisible(false);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
       
}//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        bahan_kimia.setVisible(false);

}//GEN-LAST:event_jButton14ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        air_produksi.setVisible(false);
        bersih_layar_setor();
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
}//GEN-LAST:event_jButton7ActionPerformed

    private void tek_cari_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tek_cari_anggotaActionPerformed
        // TODO add your handling code here:
        String cari = tek_cari_anggota.getText();
        if (cari.isEmpty() || cari.equalsIgnoreCase("") || cari == null) {
            try {
                tampilAnggota();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else {
            try {
                tampilAnggota(cari);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_tek_cari_anggotaActionPerformed

    private void tek_cari_anggotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tek_cari_anggotaKeyTyped
        // TODO add your handling code here:
        String cari = tek_cari_anggota.getText();
        if (cari.isEmpty() || cari.equalsIgnoreCase("") || cari == null) {
            try {
                tampilAnggota();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else {
            try {
                tampilAnggota(cari);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_tek_cari_anggotaKeyTyped

    private void tabel_cari_anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_cari_anggotaMouseClicked
        
    }//GEN-LAST:event_tabel_cari_anggotaMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new Beranda().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void tek_jumlah_pinjam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tek_jumlah_pinjam1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tek_jumlah_pinjam1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        air_baku.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        air_produksi.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        bahan_bakar.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        pemakaian_listrik.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        data_pelanggan.setVisible(true);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        pemakaian_air.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        pemompaan_distribusi.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        pencucian_pipa.setVisible(true);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        biaya_lab.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        bahan_kimia.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed
    public static String bulan(int b) {
        String bb = "";
        if (b == 1) {
            bb = "JAN";
        } else if (b == 2) {
            bb = "FEB";
        } else if (b == 3) {
            bb = "MAR";
        } else if (b == 4) {
            bb = "APR";
        } else if (b == 5) {
            bb = "MAY";
        } else if (b == 6) {
            bb = "JUN";
        } else if (b == 7) {
            bb = "JUL";
        } else if (b == 8) {
            bb = "AUG";
        } else if (b == 9) {
            bb = "SEP";
        } else if (b == 10) {
            bb = "OKT";
        } else if (b == 11) {
            bb = "NOV";
        } else if (b == 12) {
            bb = "DEC";
        }
        return bb;
    }

    public void tampilSimpanan(String nik) throws Exception {
//        List<Simpanan> a = Kontrol_Simpanan.getKoneksi().getAllSimpanan(nik);
//        Tabel_Model_Daftar_Simpanan model = new Tabel_Model_Daftar_Simpanan(a);
//        tabel_Daftar_Simpanan.setModel(model);
    }

    public void tampilPinjaman(String nik) throws Exception {
//        List<Pinjaman> a = Kontrol_Pinjaman.getKoneksi().getAllPinjaman(nik);
//        Tabel_Model_Daftar_Pinjaman model = new Tabel_Model_Daftar_Pinjaman(a);
//        tabel_Daftar_Pinjaman.setModel(model);
    }

    public void STATUSPinjaman(String nik) throws Exception {
//        List<Pinjaman> a = Kontrol_Pinjaman.getKoneksi().getAllPinjaman(nik);
//        double p = 0;
//        for (int i = 0; i < a.size(); i++) {
//            p += (a.get(i).getSaldo_Pokok_pinjaman() + a.get(i).getSaldo_Bunga());
//        }
//        if (p > 0) {
//            label_status_pinjam.setText(": Pinjam");
//        }
    }

    public void tampilAnggota() throws Exception {
        List<Anggota> a = Kontrol_Anggota.getKoneksi().getAllAnggota();
        Tabel_Model_Cari_Anggota model = new Tabel_Model_Cari_Anggota(a);
        tabel_cari_anggota.setModel(model);
    }

    public void tampilAnggota(String key) throws Exception {
        List<Anggota> a = Kontrol_Anggota.getKoneksi().CariAllAnggota(key);
        Tabel_Model_Cari_Anggota model = new Tabel_Model_Cari_Anggota(a);
        tabel_cari_anggota.setModel(model);
    }

    public void bersih_layar_setor() {

        tek_nominal_setor_wajib.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
            java.awt.EventQueue.invokeLater(new Runnable() {

                public void run() {
                    new AirBersih().setVisible(true);
                }
            });
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog air_baku;
    private javax.swing.JDialog air_produksi;
    private javax.swing.JDialog bahan_bakar;
    private javax.swing.JDialog bahan_kimia;
    private javax.swing.JDialog biaya_lab;
    private javax.swing.JDialog data_pelanggan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel label_tgl_angsur;
    private javax.swing.JDialog pemakaian_air;
    private javax.swing.JDialog pemakaian_listrik;
    private javax.swing.JDialog pemompaan_distribusi;
    private javax.swing.JDialog pencucian_pipa;
    private javax.swing.JTable tabel_cari_anggota;
    private javax.swing.JTextField tek_cari_anggota;
    private javax.swing.JTextField tek_jumlah_pinjam;
    private javax.swing.JTextField tek_jumlah_pinjam1;
    private javax.swing.JTextField tek_nominal_setor_Sukarela;
    private javax.swing.JTextField tek_nominal_setor_Sukarela1;
    private javax.swing.JTextField tek_nominal_setor_Sukarela2;
    private javax.swing.JTextField tek_nominal_setor_Sukarela3;
    private javax.swing.JTextField tek_nominal_setor_Sukarela4;
    private javax.swing.JTextField tek_nominal_setor_Sukarela5;
    private javax.swing.JTextField tek_nominal_setor_wajib;
    private javax.swing.JTextField tek_nominal_setor_wajib1;
    private javax.swing.JTextField tek_nominal_setor_wajib2;
    private javax.swing.JTextField tek_nominal_setor_wajib3;
    private javax.swing.JTextField tek_nominal_setor_wajib4;
    private javax.swing.JTextField tek_nominal_setor_wajib5;
    private javax.swing.JTextField tek_nominal_tarik;
    private javax.swing.JTextField tek_nominal_tarik1;
    private com.toedter.calendar.JDateChooser tgl_setoran1;
    private com.toedter.calendar.JDateChooser tgl_setoran2;
    private com.toedter.calendar.JDateChooser tgl_setoran3;
    private com.toedter.calendar.JDateChooser tgl_setoran4;
    private com.toedter.calendar.JDateChooser tgl_setoran5;
    // End of variables declaration//GEN-END:variables
}
