/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tambah_Anggota.java
 *
 * Created on May 8, 2014, 9:46:13 PM
 */
package bumdes;

import Kontrol.ProfilKontrol;
import Tabel_Model.Bumdes;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author Rafael Aweng
 */
public class Profile extends javax.swing.JFrame {

    Bumdes bum;
    String file = "../gambar/bg.jpg";

    /** Creates new form Tambah_Anggota */
    public Profile() {
        initComponents();
        this.setLocationRelativeTo(null);
        updateDesa();
        updateBumdes();
        updatePengurus();
    }

    public void updateDesa() {
        try {
            bum = ProfilKontrol.getKoneksi().tampilBumdes();
            namaDesa_text.setText(bum.getNamaDesa());
            alamatDesa_text.setText(bum.getAlamatDesa());
            provinsi_text.setText(bum.getProvinsiDesa());
            kabupaten_text.setText(bum.getKabupaten());
            kecamatan_text.setText(bum.getKecamatan());
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    public void updateBumdes() {
        try {
            bum = ProfilKontrol.getKoneksi().tampilBumdes();
            namaBumdes_text.setText(bum.getNamaBumdes());
            alamat_text.setText(bum.getAlamatBumdes());
            telp_text.setText(bum.getNoTelpBumdes());
            web_text.setText(bum.getWebBumdes());
            email_text.setText(bum.getEmailBumdes());
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    public void updatePengurus() {
        try {
            bum = ProfilKontrol.getKoneksi().tampilBumdes();
            dewanKom_text.setText(bum.getDewanKomisaris());
            direksi_text.setText(bum.getDireksi());
            kaDesa_text.setText(bum.getKa_desa());
            badanPengawas_text.setText(bum.getBadanPengawas());
            tahun_text.setText(bum.getTahun());
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        provinsi_text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namaDesa_text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        kabupaten_text = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        kecamatan_text = new javax.swing.JTextField();
        tombol_Simpan1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatDesa_text = new javax.swing.JTextArea();
        tombol_Simpan_Anggota3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        telp_text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        namaBumdes_text = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        web_text = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        email_text = new javax.swing.JTextField();
        tombol_Simpan2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        alamat_text = new javax.swing.JTextArea();
        tombol_Simpan_Anggota4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        kaDesa_text = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dewanKom_text = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        badanPengawas_text = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tahun_text = new javax.swing.JTextField();
        tombol_Simpan3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        direksi_text = new javax.swing.JTextField();
        tombol_Simpan_Anggota5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRANSAKSI SIMPAN & PINJAM");

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMASI PROFIL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Times New Roman", 3, 24))); // NOI18N

        jPanel10.setBackground(new java.awt.Color(204, 204, 0));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jButton8.setText("KEMBALI");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(831, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROFIL DESA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        provinsi_text.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("PROVINSI");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("NAMA DESA");

        namaDesa_text.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("KABUPATEN");

        kabupaten_text.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("KECAMATAN");

        kecamatan_text.setEnabled(false);

        tombol_Simpan1.setFont(new java.awt.Font("Times New Roman", 0, 12));
        tombol_Simpan1.setText("SIMPAN");
        tombol_Simpan1.setEnabled(false);
        tombol_Simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_Simpan1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("ALAMAT");

        alamatDesa_text.setColumns(20);
        alamatDesa_text.setRows(5);
        alamatDesa_text.setEnabled(false);
        jScrollPane2.setViewportView(alamatDesa_text);

        tombol_Simpan_Anggota3.setFont(new java.awt.Font("Times New Roman", 0, 12));
        tombol_Simpan_Anggota3.setText("EDIT");
        tombol_Simpan_Anggota3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_Simpan_Anggota3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(tombol_Simpan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol_Simpan_Anggota3))
                    .addComponent(provinsi_text, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(kabupaten_text, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(kecamatan_text, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(namaDesa_text, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaDesa_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(provinsi_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kabupaten_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(kecamatan_text))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombol_Simpan1)
                    .addComponent(tombol_Simpan_Anggota3))
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(204, 204, 0));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROFIL BUMDES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        telp_text.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("TELP/HP");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("NAMA BUMDES");

        namaBumdes_text.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("WEB");

        web_text.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("EMAIL");

        email_text.setEnabled(false);

        tombol_Simpan2.setFont(new java.awt.Font("Times New Roman", 0, 12));
        tombol_Simpan2.setText("SIMPAN");
        tombol_Simpan2.setEnabled(false);
        tombol_Simpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_Simpan2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("ALAMAT");

        alamat_text.setColumns(20);
        alamat_text.setRows(5);
        alamat_text.setEnabled(false);
        jScrollPane3.setViewportView(alamat_text);

        tombol_Simpan_Anggota4.setFont(new java.awt.Font("Times New Roman", 0, 12));
        tombol_Simpan_Anggota4.setText("EDIT");
        tombol_Simpan_Anggota4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_Simpan_Anggota4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(tombol_Simpan2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tombol_Simpan_Anggota4))
                    .addComponent(email_text, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(web_text, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(telp_text, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(namaBumdes_text, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(namaBumdes_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(telp_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(web_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(email_text))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombol_Simpan2)
                    .addComponent(tombol_Simpan_Anggota4))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(204, 204, 0));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROFIL KEPENGURUSAN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        kaDesa_text.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("KEP.UNIT DESA");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("DEWAN KOMISARIS");

        dewanKom_text.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("BADAN PEGAWAS");

        badanPengawas_text.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("TAHUN");

        tahun_text.setEnabled(false);

        tombol_Simpan3.setFont(new java.awt.Font("Times New Roman", 0, 12));
        tombol_Simpan3.setText("SIMPAN");
        tombol_Simpan3.setEnabled(false);
        tombol_Simpan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_Simpan3ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("DIREKSI");

        direksi_text.setEnabled(false);

        tombol_Simpan_Anggota5.setFont(new java.awt.Font("Times New Roman", 0, 12));
        tombol_Simpan_Anggota5.setText("EDIT");
        tombol_Simpan_Anggota5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_Simpan_Anggota5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol_Simpan3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol_Simpan_Anggota5)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kaDesa_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(direksi_text, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(dewanKom_text, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(badanPengawas_text, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(tahun_text, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(dewanKom_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(direksi_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kaDesa_text))
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(badanPengawas_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tahun_text))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombol_Simpan3)
                    .addComponent(tombol_Simpan_Anggota5))
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Beranda().setVisible(true);
}//GEN-LAST:event_jButton8ActionPerformed

    private void tombol_Simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_Simpan1ActionPerformed
        Bumdes bum = new Bumdes();
        bum.setNamaDesa(namaDesa_text.getText());
        bum.setAlamatDesa(alamatDesa_text.getText());
        bum.setProvinsiDesa(provinsi_text.getText());
        bum.setKabupaten(kabupaten_text.getText());
        bum.setKecamatan(kecamatan_text.getText());
        try {
            ProfilKontrol.getKoneksi().ubahDesa(bum);
            JOptionPane.showMessageDialog(this, "Profil Desa Berhasil Disimpan");
            matiTeksDesa();
            updateDesa();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Profil Desa GAGAL Disimpan");
            Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tombol_Simpan1ActionPerformed

    private void tombol_Simpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_Simpan2ActionPerformed
        // TODO add your handling code here:
        Bumdes bum = new Bumdes();
        bum.setNamaBumdes(namaBumdes_text.getText());
        bum.setAlamatBumdes(alamat_text.getText());
        bum.setNoTelpBumdes(telp_text.getText());
        bum.setWebBumdes(web_text.getText());
        bum.setEmailBumdes(email_text.getText());
        try {
            ProfilKontrol.getKoneksi().ubahBumdes(bum);
            JOptionPane.showMessageDialog(this, "Profil Bumdes Berhasil Disimpan");
            matiTeksBumDesa();
            updateBumdes();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Profil Bumdes GAGAL Disimpan");
            Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tombol_Simpan2ActionPerformed

    private void tombol_Simpan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_Simpan3ActionPerformed
        // TODO add your handling code here:
        Bumdes bum = new Bumdes();
        bum.setDewanKomisaris(dewanKom_text.getText());
        bum.setDireksi(direksi_text.getText());
        bum.setKa_desa(kaDesa_text.getText());
        bum.setBadanPengawas(badanPengawas_text.getText());
        bum.setTahun(tahun_text.getText());
        try {
            ProfilKontrol.getKoneksi().ubahKepengurusan(bum);
            JOptionPane.showMessageDialog(this, "Profil Kepengurusan Berhasil Disimpan");
            matiTeksPengurus();
            updatePengurus();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Profil Kepengurusan Berhasil Disimpan");
            Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tombol_Simpan3ActionPerformed

    private void tombol_Simpan_Anggota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_Simpan_Anggota3ActionPerformed
        // TODO add your handling code here:
        hidupTeksDesa();

    }//GEN-LAST:event_tombol_Simpan_Anggota3ActionPerformed

    private void tombol_Simpan_Anggota4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_Simpan_Anggota4ActionPerformed
        // TODO add your handling code here:
        hidupTeksBumDesa();
    }//GEN-LAST:event_tombol_Simpan_Anggota4ActionPerformed

    private void tombol_Simpan_Anggota5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_Simpan_Anggota5ActionPerformed
        // TODO add your handling code here:
        hidupTeksPengurus();
    }//GEN-LAST:event_tombol_Simpan_Anggota5ActionPerformed
    public void hidupTeksDesa() {
        tombol_Simpan1.setEnabled(true);
        namaDesa_text.setEnabled(true);
        alamatDesa_text.setEnabled(true);
        provinsi_text.setEnabled(true);
        kabupaten_text.setEnabled(true);
        kecamatan_text.setEnabled(true);
    }

    public void matiTeksDesa() {
        tombol_Simpan1.setEnabled(false);
        namaDesa_text.setEnabled(false);
        alamatDesa_text.setEnabled(false);
        provinsi_text.setEnabled(false);
        kabupaten_text.setEnabled(false);
        kecamatan_text.setEnabled(false);
    }

    public void hidupTeksBumDesa() {
        tombol_Simpan2.setEnabled(true);
        namaBumdes_text.setEnabled(true);
        alamat_text.setEnabled(true);
        telp_text.setEnabled(true);
        web_text.setEnabled(true);
        email_text.setEnabled(true);
    }

    public void matiTeksBumDesa() {
        tombol_Simpan2.setEnabled(false);
        namaBumdes_text.setEnabled(false);
        alamat_text.setEnabled(false);
        telp_text.setEnabled(false);
        web_text.setEnabled(false);
        email_text.setEnabled(false);
    }

    public void hidupTeksPengurus() {
        tombol_Simpan3.setEnabled(true);
        dewanKom_text.setEnabled(true);
        direksi_text.setEnabled(true);
        kaDesa_text.setEnabled(true);
        badanPengawas_text.setEnabled(true);
        tahun_text.setEnabled(true);
    }

    public void matiTeksPengurus() {
        tombol_Simpan3.setEnabled(false);
        dewanKom_text.setEnabled(false);
        direksi_text.setEnabled(false);
        kaDesa_text.setEnabled(false);
        badanPengawas_text.setEnabled(false);
        tahun_text.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
            java.awt.EventQueue.invokeLater(new Runnable() {

                public void run() {
                    new Profile().setVisible(true);
                }
            });
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatDesa_text;
    private javax.swing.JTextArea alamat_text;
    private javax.swing.JTextField badanPengawas_text;
    private javax.swing.JTextField dewanKom_text;
    private javax.swing.JTextField direksi_text;
    private javax.swing.JTextField email_text;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField kaDesa_text;
    private javax.swing.JTextField kabupaten_text;
    private javax.swing.JTextField kecamatan_text;
    private javax.swing.JTextField namaBumdes_text;
    private javax.swing.JTextField namaDesa_text;
    private javax.swing.JTextField provinsi_text;
    private javax.swing.JTextField tahun_text;
    private javax.swing.JTextField telp_text;
    private javax.swing.JButton tombol_Simpan1;
    private javax.swing.JButton tombol_Simpan2;
    private javax.swing.JButton tombol_Simpan3;
    private javax.swing.JButton tombol_Simpan_Anggota3;
    private javax.swing.JButton tombol_Simpan_Anggota4;
    private javax.swing.JButton tombol_Simpan_Anggota5;
    private javax.swing.JTextField web_text;
    // End of variables declaration//GEN-END:variables
}
