/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Custom.RataKanan;
import Kelas.Barang;
import Kelas.Profil;
import Custom.Tanggal;
import Kelas.Anggota;
import Kelas.Pengeluaran;
import Kelas.Trans;
import Kelas.Transaksi;
import Koneksi.Koneksi;
import Kontrol.BarangKontrol;
import Kontrol.PengaturanKontrol;
import Kontrol.PengeluaranKontrol;
import Kontrol.TransKontrol;
import Kontrol.TransaksiKontrol;
import TabelModel.TransaksiKeluarTM;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author damaikurnia
 */
public class FormTransaksiPengeluaran extends javax.swing.JFrame {

    /**
     * Creates new form FormAir
     */
    public FormTransaksiPengeluaran() {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
//            setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);

            dialog_pembelian.setVisible(false);
            dialog_pembelian.setSize(688, 475);
            dialog_pembelian.setLocationRelativeTo(null);
            dialog_pembelian.setTitle("DATA ANGGOTA");
            update();
            isiList();

            sinkronGambar();
            GregorianCalendar gc = new GregorianCalendar();
            date_dari.setDate(gc.getTime());
            date_sampai.setDate(gc.getTime());
            date_tanggal.setDate(gc.getTime());

            String bulan = generateBulanTahun(Tanggal.getTanggal2());
            label_bulan.setText(bulan.split("-")[0]);
            combo_pengeluaran.setEnabled(false);
            label_tanggal.setText(Tanggal.getTanggal());

            button_cetak.setVisible(false);
            jLabel8.setText("TRANSAKSI BULAN INI (" + label_bulan.getText() + ")");
        } catch (SQLException ex) {
            Logger.getLogger(FormTransaksiPengeluaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_pembelian = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        date_dari = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        date_sampai = new com.toedter.calendar.JDateChooser();
        button_tampil = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_pengeluaran2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        text_ttlbeliall = new javax.swing.JTextField();
        button_cetak = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_namaDesa = new javax.swing.JLabel();
        label_alamatNotelp = new javax.swing.JLabel();
        label_kop = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        button_ubah = new javax.swing.JButton();
        button_tabel = new javax.swing.JButton();
        text_noTrans = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        label_tanggal = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        text_total = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pengeluaran = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        combo_pengeluaran = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        text_totalBulan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        date_tanggal = new com.toedter.calendar.JDateChooser();
        label_bulan = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        dialog_pembelian.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TABEL SELURUH TRANSAKSI PENGELUARAN");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 40));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 60));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("TAMPIL BERDASARKAN");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("TANGGAL");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        date_dari.setDateFormatString("dd-MMM-yyyy");
        jPanel6.add(date_dari, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 150, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("-");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 10, 30));

        date_sampai.setDateFormatString("dd-MMM-yyyy");
        jPanel6.add(date_sampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 150, 30));

        button_tampil.setText("TAMPIL");
        button_tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tampilActionPerformed(evt);
            }
        });
        jPanel6.add(button_tampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, 30));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 670, 70));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_pengeluaran2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabel_pengeluaran2);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 650, 220));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("TOTAL TRANSAKSI BELI");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 130, 20));

        text_ttlbeliall.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel7.add(text_ttlbeliall, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 170, -1));

        button_cetak.setText("CETAK");
        button_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cetakActionPerformed(evt);
            }
        });
        jPanel7.add(button_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 170, 30));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 670, 300));

        dialog_pembelian.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 430));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SISTEM INFORMASI PENGELOLAAN AIR BERSIH");

        label_namaDesa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_namaDesa.setText("BADAN USAHA MILIK DESA <<NAMA DESA>>");

        label_alamatNotelp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_alamatNotelp.setText("<<ALAMAT, NO TELP>>");

        label_kop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(label_kop, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_namaDesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_alamatNotelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_namaDesa, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_alamatNotelp)
                .addContainerGap(17, Short.MAX_VALUE))
            .addComponent(label_kop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FORM TRANSAKSI PENGELUARAN BIAYA");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PENGELUARAN");

        button_ubah.setText("UBAH");
        button_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ubahActionPerformed(evt);
            }
        });

        button_tabel.setText("LIHAT TRANSAKSI PENGELUARAN BULAN LALU");
        button_tabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tabelActionPerformed(evt);
            }
        });

        text_noTrans.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("NO TRANSAKSI");

        label_tanggal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_tanggal.setText("Selasa, 17 Februari 2015");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("TANGGAL TRANSAKSI");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("JUMLAH PENGELUARAN (Rp)");

        text_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        text_total.setText("0");

        tabel_pengeluaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_pengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pengeluaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_pengeluaran);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TOTAL TRANSAKSI PENGELUARAN BULAN INI");

        combo_pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_pengeluaranActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TRANSAKSI BULAN INI");

        text_totalBulan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Hari, Tanggal");

        date_tanggal.setDateFormatString("dd-MM-yyyy");

        label_bulan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_bulan.setText("label_bulan");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addComponent(text_totalBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(label_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(384, 384, 384)
                                .addComponent(jLabel16)
                                .addGap(20, 20, 20)
                                .addComponent(label_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(text_noTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(combo_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(date_tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(text_total)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(button_ubah)
                        .addGap(84, 84, 84)
                        .addComponent(button_tabel)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(label_bulan))
                    .addComponent(label_tanggal))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel15))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_pengeluaran)
                            .addComponent(text_noTrans)
                            .addComponent(text_total)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date_tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(26, 26, 26)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_totalBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_ubah)
                    .addComponent(button_tabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setBackground(java.awt.Color.black);
        jMenu1.setText("HOME");
        jMenu1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(java.awt.Color.black);
        jMenu2.setText("BARANG");
        jMenu2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jMenuItem2.setBackground(java.awt.Color.white);
        jMenuItem2.setForeground(java.awt.Color.black);
        jMenuItem2.setText("Registrasi Barang");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setBackground(java.awt.Color.white);
        jMenuItem3.setForeground(java.awt.Color.black);
        jMenuItem3.setText("Pembelian Barang");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem13.setBackground(java.awt.Color.white);
        jMenuItem13.setForeground(java.awt.Color.black);
        jMenuItem13.setText("Pemakaian Barang");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(java.awt.Color.black);
        jMenu3.setText("PELANGGAN");
        jMenu3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jMenuItem9.setBackground(java.awt.Color.white);
        jMenuItem9.setForeground(java.awt.Color.black);
        jMenuItem9.setText("Pendaftaran Pelanggan Baru");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setBackground(java.awt.Color.white);
        jMenuItem10.setForeground(java.awt.Color.black);
        jMenuItem10.setText("Pemakaian Air Pelanggan");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setBackground(java.awt.Color.white);
        jMenuItem11.setForeground(java.awt.Color.black);
        jMenuItem11.setText("Pembayaran Rekening Air");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem7.setBackground(java.awt.Color.white);
        jMenuItem7.setForeground(java.awt.Color.black);
        jMenuItem7.setText("Informasi Keluhan Pelanggan");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(java.awt.Color.black);
        jMenu4.setText("PENGELUARAN");
        jMenu4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jMenuItem1.setBackground(java.awt.Color.white);
        jMenuItem1.setForeground(java.awt.Color.black);
        jMenuItem1.setText("List Pengeluaran");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem5.setBackground(java.awt.Color.white);
        jMenuItem5.setForeground(java.awt.Color.black);
        jMenuItem5.setText("Pengeluaran Bulanan");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setBackground(java.awt.Color.white);
        jMenuItem6.setForeground(java.awt.Color.black);
        jMenuItem6.setText("Pembayaran Hutang");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        jMenu5.setBackground(java.awt.Color.black);
        jMenu5.setText("LAPORAN");
        jMenu5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jMenuItem4.setBackground(java.awt.Color.white);
        jMenuItem4.setForeground(java.awt.Color.black);
        jMenuItem4.setText("Laba - Rugi");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem12.setBackground(java.awt.Color.white);
        jMenuItem12.setForeground(java.awt.Color.black);
        jMenuItem12.setText("Neraca");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuBar1.add(jMenu5);

        jMenu6.setBackground(java.awt.Color.black);
        jMenu6.setText("PENGATURAN");
        jMenu6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jMenuItem8.setBackground(java.awt.Color.white);
        jMenuItem8.setForeground(java.awt.Color.black);
        jMenuItem8.setText("Profil Desa");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_tabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tabelActionPerformed
        dialog_pembelian.setVisible(true);
    }//GEN-LAST:event_button_tabelActionPerformed

    private void tabel_pengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pengeluaranMouseClicked
        int row1 = tabel_pengeluaran.getSelectedRow();
        if (!tabel_pengeluaran.getValueAt(row1, 3).toString().equals("0")) {
            JOptionPane.showMessageDialog(null, "Anda tidak dapat mengubah data!");
        } else {
            text_noTrans.setText(tabel_pengeluaran.getValueAt(row1, 1).toString());
            combo_pengeluaran.setSelectedItem(tabel_pengeluaran.getValueAt(row1, 2).toString());
            text_total.setText(tabel_pengeluaran.getValueAt(row1, 3).toString());

            customnya();
        }
    }//GEN-LAST:event_tabel_pengeluaranMouseClicked

    private void button_tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tampilActionPerformed
        String tglDari = new SimpleDateFormat("yyyy-MM-dd").format(date_dari.getDate());
        String tglSampai = new SimpleDateFormat("yyyy-MM-dd").format(date_sampai.getDate());
        update2(tglDari, tglSampai);
    }//GEN-LAST:event_button_tampilActionPerformed

    private void button_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cetakActionPerformed
        Connection kon = new Koneksi().getConnection();
        String reportSource = "./src/Lap/LapTransaksiPembelian.jasper";
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("tDari", new SimpleDateFormat("yyyy-MM-dd").format(date_dari.getDate()));
        params.put("tSampai", new SimpleDateFormat("yyyy-MM-dd").format(date_sampai.getDate()));
        try {
            JasperPrint jasperPrint = JasperFillManager.fillReport(reportSource, params, kon);
            JasperViewer.viewReport(jasperPrint, false);

        } catch (JRException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_button_cetakActionPerformed

    private void button_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ubahActionPerformed
        try {
            String kodeAkun = TransaksiKontrol.getKoneksi().keluar_tampilKodeAkun(text_noTrans.getText());
            Transaksi trans = new Transaksi();
            trans.setNoTrans(text_noTrans.getText());
            trans.setTanggalTransaksi(new SimpleDateFormat("yyyy-MM-dd").format(date_tanggal.getDate()));
            trans.setTotal(Double.parseDouble(text_total.getText()));

            TransaksiKontrol.getKoneksi().keluar_updateTransaksi(trans);
            
            //pembayaran beban kas (kredit), modal (kredit), beban x (debit) -- nanti beban ga usah diakumulasi lagi karena sudah dikurangi di modal
            Trans beban = new Trans(kodeAkun, (long) trans.getTotal(), 0);
            Trans kas = new Trans("1.1.1", 0, (long) trans.getTotal());
            Trans modal = new Trans("3.1.1", 0, (long) trans.getTotal());
            
            TransKontrol.getKoneksi().insertTransaksi(beban);
            TransKontrol.getKoneksi().insertTransaksi(kas);
            TransKontrol.getKoneksi().insertTransaksi(modal);
            JOptionPane.showMessageDialog(null, "Update Pengeluaran berhasil!");
            update();
//            defaultnya();
        } catch (SQLException ex) {
            Logger.getLogger(FormTransaksiPengeluaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_ubahActionPerformed

    private void combo_pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_pengeluaranActionPerformed
        try {
            List<Pengeluaran> pen = PengeluaranKontrol.getKoneksi().selectPengeluaran2(combo_pengeluaran.getSelectedItem().toString());
            String tanggal[] = Tanggal.getTanggal2().split("-");
            text_noTrans.setText(pen.get(0).getKode() + "-" + tanggal[0] + tanggal[1]);
        } catch (SQLException ex) {
            Logger.getLogger(FormTransaksiPengeluaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_combo_pengeluaranActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        FormAir a = new FormAir();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FormBarang a = new FormBarang();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FormTransaksiPembelian a = new FormTransaksiPembelian();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        FormTransaksiPemakaianBarang a = new FormTransaksiPemakaianBarang();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        FormAnggota a = new FormAnggota();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        FormPemakaianAir a = new FormPemakaianAir();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        FormTransaksiPenjualan a = new FormTransaksiPenjualan();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        FormKeluhan a = new FormKeluhan();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FormPengeluaran a = new FormPengeluaran();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        FormTransaksiPengeluaran a = new FormTransaksiPengeluaran();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        FormTransaksiPembayaranHutang a = new FormTransaksiPembayaranHutang();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FormLabaRugi a = new FormLabaRugi();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        FormNeraca a = new FormNeraca();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        FormPengaturan a = new FormPengaturan();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    public void update() {
        try {
            List<Transaksi> agt = TransaksiKontrol.getKoneksi().keluar_selectTransaksi();
            List<Pengeluaran> pen = PengeluaranKontrol.getKoneksi().selectPengeluaran2("");
            if (agt.size() == 0) {
                for (int i = 0; i < pen.size(); i++) {
                    String kodeAkun = "";
                    if (Integer.parseInt(pen.get(i).getKode().split("-")[1]) <= 5) {
                        kodeAkun = "5.1." + Integer.parseInt(pen.get(i).getKode().split("-")[1]);
                    } else {
                        kodeAkun = "5.1.6";
                    }
                    Transaksi trans = new Transaksi();
                    String tanggal[] = Tanggal.getTanggal2().split("-");
                    trans.setNoTrans(pen.get(i).getKode() + "-" + tanggal[0] + tanggal[1]);
                    trans.setIdBarang(new Barang(pen.get(i).getKode(), pen.get(i).getNamaPengeluaran(), i, i, ""));
                    trans.setIdAnggota(new Anggota("-", null, null, null, null, null, i, i, null, null, null, null, null));
                    trans.setTanggalTransaksi(Tanggal.getTanggal2());
                    trans.setJenisTransaksi("PENGELUARAN");
                    trans.setJumlah(0);
                    trans.setHargaSatuan(0);
                    trans.setDenda(0);
                    trans.setTotal(0);
                    TransaksiKontrol.getKoneksi().keluar_insertTransaksi(trans);
                }
                agt = TransaksiKontrol.getKoneksi().keluar_selectTransaksi();
                TransaksiKeluarTM model = new TransaksiKeluarTM(agt);
                tabel_pengeluaran.setModel(model);

                TableCellRenderer kanan = new RataKanan();
//            tabel_pengeluaran.getColumnModel().getColumn(2).setCellRenderer(kanan);
                tabel_pengeluaran.getColumnModel().getColumn(3).setCellRenderer(kanan);
//            tabel_pengeluaran.getColumnModel().getColumn(4).setCellRenderer(kanan);

                text_totalBulan.setText(TransaksiKontrol.getKoneksi().keluar_tampilTotalKeluarBulanIni());
            } else if (agt.size() != pen.size()) {
                JOptionPane.showMessageDialog(null, "Gak size");
                for (int i = 0; i < pen.size(); i++) {
                    boolean cek = false;
                    for (int j = 0; j < agt.size(); j++) {
                        if (pen.get(i).getKode().equals(agt.get(j).getIdBarang().getIdBarang())) {
                            cek = true;
                        } else {
                            cek = cek;
                        }

                    }
                    if (cek == false) {
                        Transaksi trans = new Transaksi();
                        String tanggal[] = Tanggal.getTanggal2().split("-");
                        trans.setNoTrans(pen.get(i).getKode() + "-" + tanggal[0] + tanggal[1]);
                        trans.setIdBarang(new Barang(pen.get(i).getKode(), pen.get(i).getNamaPengeluaran(), i, i, ""));
                        trans.setIdAnggota(new Anggota("-", null, null, null, null, null, i, i, null, null, null, null, null));
                        trans.setTanggalTransaksi(Tanggal.getTanggal2());
                        trans.setJenisTransaksi("PENGELUARAN");
                        trans.setJumlah(0);
                        trans.setHargaSatuan(0);
                        trans.setDenda(0);
                        trans.setTotal(0);
                        TransaksiKontrol.getKoneksi().keluar_insertTransaksi(trans);
                    }
                }
                agt = TransaksiKontrol.getKoneksi().keluar_selectTransaksi();
                TransaksiKeluarTM model = new TransaksiKeluarTM(agt);
                tabel_pengeluaran.setModel(model);

                TableCellRenderer kanan = new RataKanan();
//            tabel_pengeluaran.getColumnModel().getColumn(2).setCellRenderer(kanan);
                tabel_pengeluaran.getColumnModel().getColumn(3).setCellRenderer(kanan);
//            tabel_pengeluaran.getColumnModel().getColumn(4).setCellRenderer(kanan);

                text_totalBulan.setText(TransaksiKontrol.getKoneksi().keluar_tampilTotalKeluarBulanIni());
            } else {

                TransaksiKeluarTM model = new TransaksiKeluarTM(agt);
                tabel_pengeluaran.setModel(model);

                TableCellRenderer kanan = new RataKanan();
//            tabel_pengeluaran.getColumnModel().getColumn(2).setCellRenderer(kanan);
                tabel_pengeluaran.getColumnModel().getColumn(3).setCellRenderer(kanan);
//            tabel_pengeluaran.getColumnModel().getColumn(4).setCellRenderer(kanan);

                text_totalBulan.setText(TransaksiKontrol.getKoneksi().keluar_tampilTotalKeluarBulanIni());
//        tabelDosen.getColumnModel().getColumn(0).setMinWidth(70);
//        tabelDosen.getColumnModel().getColumn(0).setMaxWidth(70);
//        tabelDosen.getColumnModel().getColumn(1).setMinWidth(220);
//        tabelDosen.getColumnModel().getColumn(1).setMaxWidth(220);
//            tabelDosen.setDefaultRenderer(Object.class, new renderWarnaWarni(Color.lightGray, Color.white));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormAnggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void update2(String tglDari, String tglSampai) {
        try {
            List<Transaksi> agt = TransaksiKontrol.getKoneksi().keluar_selectTransaksi2(tglDari, tglSampai);

            TransaksiKeluarTM model = new TransaksiKeluarTM(agt);
            tabel_pengeluaran2.setModel(model);

            TableCellRenderer kanan = new RataKanan();
//            tabel_pengeluaran.getColumnModel().getColumn(2).setCellRenderer(kanan);
            tabel_pengeluaran2.getColumnModel().getColumn(3).setCellRenderer(kanan);
//            tabel_pengeluaran.getColumnModel().getColumn(4).setCellRenderer(kanan);

            text_ttlbeliall.setText(TransaksiKontrol.getKoneksi().keluar_tampilTotalKeluarBulanCustom(tglDari, tglSampai));
        } catch (SQLException ex) {
            Logger.getLogger(FormAnggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public String konversiBulan(String bulan) {
        if (bulan.equals("JANUARI")) {
            return "01";
        } else if (bulan.equals("FEBRUARI")) {
            return "02";
        } else if (bulan.equals("MARET")) {
            return "03";
        } else if (bulan.equals("APRIL")) {
            return "04";
        } else if (bulan.equals("MEI")) {
            return "05";
        } else if (bulan.equals("JUNI")) {
            return "06";
        } else if (bulan.equals("JULI")) {
            return "07";
        } else if (bulan.equals("AGUSTUS")) {
            return "08";
        } else if (bulan.equals("SEPTEMBER")) {
            return "09";
        } else if (bulan.equals("OKTOBER")) {
            return "10";
        } else if (bulan.equals("NOVEMBER")) {
            return "11";
        } else if (bulan.equals("DESEMBER")) {
            return "12";
        } else {
            return "-";
        }
    }

    public void isiList() throws SQLException {
        List<Pengeluaran> brg = PengeluaranKontrol.getKoneksi().selectPengeluaran2("");
        for (Pengeluaran b : brg) {
            combo_pengeluaran.addItem(b.getNamaPengeluaran());
        }
    }

    public void defaultnya() {
        button_ubah.setEnabled(false);
        text_noTrans.setText("");
        text_total.setText("0");

        text_noTrans.setEditable(true);
    }

    public void customnya() {
        button_ubah.setEnabled(true);
        combo_pengeluaran.setEnabled(false);
        text_noTrans.setEditable(false);
    }

    public void sinkronGambar() {
        try {
            Profil prof = PengaturanKontrol.getKoneksi().tampilProfil();
            label_namaDesa.setText("BADAN USAHA MILIK DESA " + prof.getNamadesa());
            label_alamatNotelp.setText(prof.getAlamatdesa() + " " + prof.getDesa() + " " + prof.getKecamatan()
                    + " " + prof.getKabupaten() + " " + prof.getProvinsi()
                    + " - " + prof.getNotelp());

            String path = new File(".").getCanonicalPath() + "/Gambar/" + prof.getLogo();

            Toolkit toolkit = Toolkit.getDefaultToolkit();
            Image image = toolkit.getImage(path);
            Image imagedResized = image.getScaledInstance(110, 100, Image.SCALE_DEFAULT);
            ImageIcon imageIcon = new ImageIcon(imagedResized);
            label_kop.setIcon(imageIcon);
        } catch (IOException ex) {
            Logger.getLogger(FormPengaturan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FormPengaturan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksiPengeluaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cetak;
    private javax.swing.JButton button_tabel;
    private javax.swing.JButton button_tampil;
    private javax.swing.JButton button_ubah;
    private javax.swing.JComboBox combo_pengeluaran;
    private com.toedter.calendar.JDateChooser date_dari;
    private com.toedter.calendar.JDateChooser date_sampai;
    private com.toedter.calendar.JDateChooser date_tanggal;
    private javax.swing.JDialog dialog_pembelian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_alamatNotelp;
    private javax.swing.JLabel label_bulan;
    private javax.swing.JLabel label_kop;
    private javax.swing.JLabel label_namaDesa;
    private javax.swing.JLabel label_tanggal;
    private javax.swing.JTable tabel_pengeluaran;
    private javax.swing.JTable tabel_pengeluaran2;
    private javax.swing.JTextField text_noTrans;
    private javax.swing.JTextField text_total;
    private javax.swing.JTextField text_totalBulan;
    private javax.swing.JTextField text_ttlbeliall;
    // End of variables declaration//GEN-END:variables

    private String generateBulanTahun(String tanggal) {
        if (tanggal.split("-")[1].equals("01")) {
            return "JANUARI-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("02")) {
            return "FEBRUARI-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("03")) {
            return "MARET-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("04")) {
            return "APRIL-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("05")) {
            return "MEI-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("06")) {
            return "JUNI-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("07")) {
            return "JULI-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("08")) {
            return "AGUSTUS-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("09")) {
            return "SEPTEMBER-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("10")) {
            return "OKTOBER-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("11")) {
            return "NOVEMBER-" + tanggal.split("-")[0];
        } else {
            return "DESEMBER-" + tanggal.split("-")[0];
        }
    }
}
