/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Custom.RataKanan;
//import Kelas.Barang;
import Kelas.Profil;
import Custom.Tanggal;
import Kelas.Anggota;
import Kelas.Pemakaian;
import Kelas.Transaksi;
import Kontrol.AnggotaKontrol;
import Kontrol.PemakaianKontrol;
import Kontrol.PengaturanKontrol;
import Kontrol.TransaksiKontrol;
import TabelModel.AnggotaTM;
import TabelModel.TransaksiJualAllTM;
import TabelModel.TransaksiJualTM;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author damaikurnia
 */
public class FormTransaksiPenjualan extends javax.swing.JFrame {

    /**
     * Creates new form FormAir
     */
    public FormTransaksiPenjualan() {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            Profil prof = PengaturanKontrol.getKoneksi().tampilProfil();
            label_namaDesa.setText("BADAN USAHA MILIK DESA " + prof.getNamadesa());
            label_alamatNotelp.setText(prof.getAlamatdesa() + " - " + prof.getNotelp());
            label_tanggal.setText(Tanggal.getTanggal());

            dialog_pembelian.setVisible(false);
            dialog_pembelian.setSize(688, 475);
            dialog_pembelian.setLocationRelativeTo(null);
            dialog_pembelian.setTitle("DATA ANGGOTA");
            label_jmlBeli.setVisible(false);

            dialog_cariP.setVisible(false);
            dialog_cariP.setSize(673, 413);
            dialog_cariP.setLocationRelativeTo(null);
            dialog_cariP.setTitle("DATA ANGGOTA");
            label_noTrans.setVisible(false);
            update();

            String bulan = Tanggal.getTanggal2().split("-")[1];
            bulan = "0" + Integer.toString(Integer.parseInt(bulan) - 1);
            combo_bulan.setSelectedItem(generateBulanTahun3(bulan));
        } catch (SQLException ex) {
            Logger.getLogger(FormTransaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_pembelian = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cb_tahun = new javax.swing.JComboBox();
        cb_tanggal = new javax.swing.JComboBox();
        cb_bulan = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_penjualan2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        text_ttlbeliall = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_penjualan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        text_ttltransbeli = new javax.swing.JTextField();
        dialog_cariP = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        text_key = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_pelanggan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_namaDesa = new javax.swing.JLabel();
        label_alamatNotelp = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        button_tambah = new javax.swing.JButton();
        button_ubah = new javax.swing.JButton();
        button_hapus = new javax.swing.JButton();
        button_tabel = new javax.swing.JButton();
        text_noPelanggan = new javax.swing.JTextField();
        label_noTrans = new javax.swing.JLabel();
        label_tanggal = new javax.swing.JLabel();
        label_jmlBeli = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        text_airdibayar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        text_hargaSatuan = new javax.swing.JTextField();
        label_status = new javax.swing.JLabel();
        text_total = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        text_airbln = new javax.swing.JTextField();
        button_pelanggan = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        text_nama = new javax.swing.JTextField();
        text_denda = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        text_airawal = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        text_pembayaran = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        combo_bulan = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        dialog_pembelian.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TABEL SELURUH TRANSAKSI PEMBELIAN");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 40));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 60));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("TANGGAL");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("TAMPIL BERDASARKAN");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        cb_tahun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "2014", "2015" }));
        cb_tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tahunActionPerformed(evt);
            }
        });
        jPanel6.add(cb_tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        cb_tanggal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cb_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tanggalActionPerformed(evt);
            }
        });
        jPanel6.add(cb_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        cb_bulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "JANUARI", "FEBRUARI", "MARET", "APRIL", "MEI", "JUNI", "JULI", "AGUSTUS", "SEPTEMBER", "OKTOBER", "NOVEMBER", "DESEMBER" }));
        cb_bulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_bulanActionPerformed(evt);
            }
        });
        jPanel6.add(cb_bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 670, 70));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_penjualan2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabel_penjualan2);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 650, 160));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("TOTAL PENDAPATAN");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 130, 20));

        text_ttlbeliall.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel7.add(text_ttlbeliall, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 170, -1));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 670, 230));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TRANSAKSI HARI INI");

        tabel_penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_penjualanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_penjualan);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TOTAL PENDAPATAN HARI INI");

        text_ttltransbeli.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_ttltransbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_ttltransbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 670, 260));

        dialog_pembelian.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 620));

        dialog_cariP.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("DATA PELANGGAN");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 640, 40));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 70));

        jLabel19.setText("KEYWORD");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, 20));

        text_key.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_keyKeyReleased(evt);
            }
        });
        jPanel8.add(text_key, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 470, -1));

        tabel_pelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pelangganMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel_pelanggan);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 620, 220));

        dialog_cariP.getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 380));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SISTEM INFORMASI PENGELOLAAN AIR BERSIH");

        label_namaDesa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_namaDesa.setText("BADAN USAHA MILIK DESA <<NAMA DESA>>");

        label_alamatNotelp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_alamatNotelp.setText("<<ALAMAT, NO TELP>>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_namaDesa, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                    .addComponent(label_alamatNotelp, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_namaDesa, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_alamatNotelp)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 110));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FORM TRANSAKSI PENJUALAN AIR");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 730, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("PEMAKAIAN AIR AWAL");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, 20));

        button_tambah.setText("TAMBAH");
        button_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tambahActionPerformed(evt);
            }
        });
        jPanel3.add(button_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        button_ubah.setText("UBAH");
        button_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ubahActionPerformed(evt);
            }
        });
        jPanel3.add(button_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        button_hapus.setText("HAPUS");
        button_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_hapusActionPerformed(evt);
            }
        });
        jPanel3.add(button_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        button_tabel.setText("TABEL TRANSAKSI PEMBELIAN");
        button_tabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tabelActionPerformed(evt);
            }
        });
        jPanel3.add(button_tabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));
        jPanel3.add(text_noPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 170, 30));

        label_noTrans.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_noTrans.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_noTrans.setText("NO PELANGGAN");
        jPanel3.add(label_noTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 30));

        label_tanggal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_tanggal.setText("Selasa, 17 Februari 2015");
        jPanel3.add(label_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 140, -1));

        label_jmlBeli.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_jmlBeli.setText("Hari, Tanggal");
        jPanel3.add(label_jmlBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 80, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("PEMAKAIAN AIR BULAN INI");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 180, -1));

        text_airdibayar.setEditable(false);
        text_airdibayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        text_airdibayar.setText("0");
        text_airdibayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_airdibayarKeyReleased(evt);
            }
        });
        jPanel3.add(text_airdibayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 170, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("DENDA ");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 120, -1));

        text_hargaSatuan.setEditable(false);
        text_hargaSatuan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        text_hargaSatuan.setText("500");
        text_hargaSatuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_hargaSatuanKeyReleased(evt);
            }
        });
        jPanel3.add(text_hargaSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 120, -1));

        label_status.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_status.setForeground(new java.awt.Color(255, 0, 51));
        label_status.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_status.setText("STATUS : ");
        jPanel3.add(label_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 330, 30));

        text_total.setEditable(false);
        text_total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        text_total.setText("0");
        jPanel3.add(text_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 200, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Hari, Tanggal");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 110, -1));

        text_airbln.setEditable(false);
        text_airbln.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        text_airbln.setText("0");
        jPanel3.add(text_airbln, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 170, -1));

        button_pelanggan.setText("...");
        button_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pelangganActionPerformed(evt);
            }
        });
        jPanel3.add(button_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 82, 40, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("PEMAKAIAN BULAN");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 140, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("PEMAKAIAN AIR BLM DIBAYAR");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 180, -1));

        text_nama.setEditable(false);
        jPanel3.add(text_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 170, -1));

        text_denda.setEditable(false);
        text_denda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        text_denda.setText("0");
        jPanel3.add(text_denda, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 120, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("HARGA SATUAN AIR");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 120, -1));

        text_airawal.setEditable(false);
        text_airawal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        text_airawal.setText("0");
        jPanel3.add(text_airawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 170, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("NO PELANGGAN");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, 120, 30));

        text_pembayaran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        text_pembayaran.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        text_pembayaran.setText("0");
        jPanel3.add(text_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 200, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("TOTAL BIAYA");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 40));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("NAMA PELANGGAN");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, 20));

        combo_bulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JANUARI", "FEBRUARI", "MARET", "APRIL", "MEI", "JUNI", "JULI", "AGUSTUS", "SEPTEMBER", "OKTOBER", "NOVEMBER", "DESEMBER" }));
        combo_bulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_bulanActionPerformed(evt);
            }
        });
        jPanel3.add(combo_bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 170, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("PEMBAYARAN");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 120, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 750, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 470));

        jMenu1.setText("HOME");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("BARANG");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("ANGGOTA");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu7.setText("INFORMASI");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem3.setText("Pemakaian Air Pelanggan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem3);

        jMenuBar1.add(jMenu7);

        jMenu4.setText("TRANSAKSI");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem1.setText("Pembelian");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("Penjualan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("LAPORAN");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem4.setText("BUM");
        jMenu5.add(jMenuItem4);

        jMenuItem5.setText("BUK");
        jMenu5.add(jMenuItem5);

        jMenuItem6.setText("JUNRAL");
        jMenu5.add(jMenuItem6);

        jMenuItem7.setText("NERACA");
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("PENGATURAN");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem8.setText("Profil Desa");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        FormAir a = new FormAir();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        FormBarang a = new FormBarang();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void button_tabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tabelActionPerformed
        dialog_pembelian.setVisible(true);
        update2("%-%");
    }//GEN-LAST:event_button_tabelActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        FormAnggota a = new FormAnggota();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FormTransaksiPembelian a = new FormTransaksiPembelian();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FormTransaksiPenjualan a = new FormTransaksiPenjualan();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        FormPengaturan a = new FormPengaturan();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void button_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tambahActionPerformed
        if (Double.parseDouble(text_total.getText()) > Double.parseDouble(text_pembayaran.getText())) {
            JOptionPane.showMessageDialog(null, "Pembayaran kurang");
        } else {
            double pembayaran = Double.parseDouble(text_pembayaran.getText());
            pembayaran = pembayaran - Double.parseDouble(text_total.getText());
            JOptionPane.showMessageDialog(null, "Kembalian Konsumen adalah : " + Double.toString(pembayaran).split("\\.")[0]);
            try {
                Transaksi trans = new Transaksi();
                trans.setNoTrans(label_noTrans.getText());
                Anggota idAnggota = new Anggota(text_noPelanggan.getText(), "", "", "", "", "", 0, 0, "", "", "", "", "");
                trans.setIdAnggota(idAnggota);
                trans.setJumlah(Integer.parseInt(text_airdibayar.getText()));
                trans.setHargaSatuan(Double.parseDouble(text_hargaSatuan.getText()));
                trans.setTotal(Double.parseDouble(text_total.getText()));

                TransaksiKontrol.getKoneksi().jual_insertTransaksi(trans);
                JOptionPane.showMessageDialog(null, "Transaksi berhasil!");

                String tanggalBln = generateBulanTahun(Tanggal.getTanggal2());
                Pemakaian pem = new Pemakaian(generateKodeBaru(trans.getNoTrans()), idAnggota,
                        Double.parseDouble(text_airbln.getText()), 0, 0, tanggalBln.split("-")[0], tanggalBln.split("-")[1]);
                PemakaianKontrol.getKoneksi().insertPemakaian(pem);

                update();
                defaultnya();
            } catch (SQLException ex) {
                Logger.getLogger(FormTransaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_button_tambahActionPerformed

    private void button_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ubahActionPerformed
//        try {
//            Transaksi trans = new Transaksi();
//            trans.setNoTrans(text_noTrans.getText());
//            Anggota idAnggota = AnggotaKontrol.getKoneksi().cariIdAnggota(combo_Anggota.getSelectedItem().toString());
//            trans.setIdAnggota(new Anggota(idAnggota.getIdAnggota(), combo_Anggota.getSelectedItem().toString(),
//                    "", "", "", "", 0, 0, "", "", "", ""));
//            trans.setJumlah(Integer.parseInt(text_jmlBeli.getText()));
//            trans.setHargaSatuan(Double.parseDouble(text_hargaSatuan.getText()));
//            trans.setTotal(Double.parseDouble(text_total.getText()));
//
//            TransaksiKontrol.getKoneksi().jual_updateTransaksi(trans);
////            Barang bar = BarangKontrol.getKoneksi().selectBarang2(idAnggota);
////            int stokSmntara = bar.getStok();
////            stokSmntara = stokSmntara - Integer.parseInt(label_jmlBeli.getText());
////            bar.setStok(stokSmntara + trans.getJumlah());
////            BarangKontrol.getKoneksi().updateBarang(bar);
////            JOptionPane.showMessageDialog(null, "Update barang berhasil!");
////            JOptionPane.showMessageDialog(null, "Stok " + bar.getNamaBarang() + " saat ini adalah = " + bar.getStok());
//            update();
//            defaultnya();
//        } catch (SQLException ex) {
//            Logger.getLogger(FormTransaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_button_ubahActionPerformed

    private void button_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_hapusActionPerformed
        try {
            Transaksi trans = new Transaksi();
            trans.setNoTrans(text_noPelanggan.getText());
            TransaksiKontrol.getKoneksi().deleteTransaksi(trans);
            update();
            defaultnya();
        } catch (SQLException ex) {
            Logger.getLogger(FormTransaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_hapusActionPerformed

    private void text_airdibayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_airdibayarKeyReleased
        if (text_airdibayar.getText().equals("")) {

        } else {
            double total = Integer.parseInt(text_airdibayar.getText())
                    * Integer.parseInt(text_hargaSatuan.getText());
            text_total.setText(Double.toString(total));
        }
    }//GEN-LAST:event_text_airdibayarKeyReleased

    private void text_hargaSatuanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_hargaSatuanKeyReleased
        if (text_hargaSatuan.getText().equals("")) {

        } else {
            double total = Integer.parseInt(text_airdibayar.getText())
                    * Integer.parseInt(text_hargaSatuan.getText());
            text_total.setText(Double.toString(total));
        }
    }//GEN-LAST:event_text_hargaSatuanKeyReleased

    private void cb_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tanggalActionPerformed
        String tanggal = cb_tanggal.getSelectedItem().toString();
        String bulan = konversiBulan(cb_bulan.getSelectedItem().toString());
        String tahun = cb_tahun.getSelectedItem().toString();

        if (!tanggal.equals("-") && bulan.equals("-") && tahun.equals("-")) {
            update2("%" + tanggal); //tanggal on, bulan off, tahun off
        } else if (!tanggal.equals("-") && !bulan.equals("-") && tahun.equals("-")) {
            update2("%" + bulan + "-" + tanggal); //tanggal on, bulan on, tahun off
        } else if (!tanggal.equals("-") && bulan.equals("-") && !tahun.equals("-")) {
            update2(tahun + "%" + tanggal); //tanggal on, bulan off, tahun on
        } else if (tanggal.equals("-") && !bulan.equals("-") && tahun.equals("-")) {
            update2("%" + bulan + "%"); //tanggal off, bulan on, tahun off
        } else if (tanggal.equals("-") && !bulan.equals("-") && !tahun.equals("-")) {
            update2(tahun + "-" + bulan + "%"); //tanggal off, bulan on, tahun on
        } else if (tanggal.equals("-") && bulan.equals("-") && !tahun.equals("-")) {
            update2(tahun + "%");//tanggal off, bulan off, tahun on
        } else if (tanggal.equals("-") && bulan.equals("-") && tahun.equals("-")) {
            update2("%-%");
        } else {
            update2(tahun + "-" + bulan + "-" + tanggal);
        }
    }//GEN-LAST:event_cb_tanggalActionPerformed

    private void cb_bulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_bulanActionPerformed
        String tanggal = cb_tanggal.getSelectedItem().toString();
        String bulan = konversiBulan(cb_bulan.getSelectedItem().toString());
        String tahun = cb_tahun.getSelectedItem().toString();

        if (!tanggal.equals("-") && bulan.equals("-") && tahun.equals("-")) {
            update2("%" + tanggal); //tanggal on, bulan off, tahun off
        } else if (!tanggal.equals("-") && !bulan.equals("-") && tahun.equals("-")) {
            update2("%" + bulan + "-" + tanggal); //tanggal on, bulan on, tahun off
        } else if (!tanggal.equals("-") && bulan.equals("-") && !tahun.equals("-")) {
            update2(tahun + "%" + tanggal); //tanggal on, bulan off, tahun on
        } else if (tanggal.equals("-") && !bulan.equals("-") && tahun.equals("-")) {
            update2("%" + bulan + "%"); //tanggal off, bulan on, tahun off
        } else if (tanggal.equals("-") && !bulan.equals("-") && !tahun.equals("-")) {
            update2(tahun + "-" + bulan + "%"); //tanggal off, bulan on, tahun on
        } else if (tanggal.equals("-") && bulan.equals("-") && !tahun.equals("-")) {
            update2(tahun + "%");//tanggal off, bulan off, tahun on
        } else if (tanggal.equals("-") && bulan.equals("-") && tahun.equals("-")) {
            update2("%-%");
        } else {
            update2(tahun + "-" + bulan + "-" + tanggal);
        }
    }//GEN-LAST:event_cb_bulanActionPerformed

    private void cb_tahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tahunActionPerformed
        String tanggal = cb_tanggal.getSelectedItem().toString();
        String bulan = konversiBulan(cb_bulan.getSelectedItem().toString());
        String tahun = cb_tahun.getSelectedItem().toString();

        if (!tanggal.equals("-") && bulan.equals("-") && tahun.equals("-")) {
            update2("%" + tanggal); //tanggal on, bulan off, tahun off
        } else if (!tanggal.equals("-") && !bulan.equals("-") && tahun.equals("-")) {
            update2("%" + bulan + "-" + tanggal); //tanggal on, bulan on, tahun off
        } else if (!tanggal.equals("-") && bulan.equals("-") && !tahun.equals("-")) {
            update2(tahun + "%" + tanggal); //tanggal on, bulan off, tahun on
        } else if (tanggal.equals("-") && !bulan.equals("-") && tahun.equals("-")) {
            update2("%" + bulan + "%"); //tanggal off, bulan on, tahun off
        } else if (tanggal.equals("-") && !bulan.equals("-") && !tahun.equals("-")) {
            update2(tahun + "-" + bulan + "%"); //tanggal off, bulan on, tahun on
        } else if (tanggal.equals("-") && bulan.equals("-") && !tahun.equals("-")) {
            update2(tahun + "%");//tanggal off, bulan off, tahun on
        } else if (tanggal.equals("-") && bulan.equals("-") && tahun.equals("-")) {
            update2("%-%");
        } else {
            update2(tahun + "-" + bulan + "-" + tanggal);
        }
    }//GEN-LAST:event_cb_tahunActionPerformed

    private void tabel_penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_penjualanMouseClicked
//        int row1 = tabel_penjualan.getSelectedRow();
//        text_noTrans.setText(tabel_penjualan.getValueAt(row1, 0).toString());
//        combo_Anggota.setSelectedItem(tabel_penjualan.getValueAt(row1, 1).toString());
//        text_jmlBeli.setText(tabel_penjualan.getValueAt(row1, 2).toString());
//        label_jmlBeli.setText(tabel_penjualan.getValueAt(row1, 2).toString());
//        text_hargaSatuan.setText(tabel_penjualan.getValueAt(row1, 3).toString());
//        text_total.setText(tabel_penjualan.getValueAt(row1, 4).toString());
//
//        customnya();
    }//GEN-LAST:event_tabel_penjualanMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FormPemakaianAir a = new FormPemakaianAir();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void button_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pelangganActionPerformed
        update("");
        dialog_cariP.setVisible(true);
    }//GEN-LAST:event_button_pelangganActionPerformed

    private void text_keyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_keyKeyReleased
//        if (text_key.getText().equals("")) {
//            update("");
//        } else {
//            update(text_key.getText());
//        }
    }//GEN-LAST:event_text_keyKeyReleased

    private void tabel_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pelangganMouseClicked
        try {
            int row1 = tabel_pelanggan.getSelectedRow();
            List<Anggota> agt = AnggotaKontrol.getKoneksi().selectAnggota2(tabel_pelanggan.getValueAt(row1, 1).toString());
            

        } catch (SQLException ex) {
            Logger.getLogger(FormTransaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabel_pelangganMouseClicked

    private void combo_bulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_bulanActionPerformed
        try {
            if (text_noPelanggan.getText().equals("")) {
            } else {
                String noPelanggan = text_noPelanggan.getText();
                String bulan = combo_bulan.getSelectedItem().toString();

                List<Anggota> agt = AnggotaKontrol.getKoneksi().selectAnggota2(noPelanggan);
                Pemakaian p = new Pemakaian("", new Anggota(noPelanggan,
                        "", "", "", "", "", 0, 0, "", "", "", "", ""), 0, 0, 0,
                        bulan, "");
                Pemakaian pem = PemakaianKontrol.getKoneksi().selectPemakaian2(p);

                text_noPelanggan.setText(pem.getIdanggota().getIdAnggota());
                text_nama.setText(agt.get(0).getNamaAnggota());
                text_airawal.setText(Double.toString(pem.getAirlunas()).split("\\.")[0]);
                text_airbln.setText(Double.toString(pem.getAirterakhir()).split("\\.")[0]);
                text_airdibayar.setText(Double.toString(pem.getAirdibayar()).split("\\.")[0]);
                label_noTrans.setText(pem.getNotransaksi());
                dialog_cariP.setVisible(false);
                label_noTrans.setVisible(true);
                String tanggal = Tanggal.getTanggal2();
                double total = Integer.parseInt(text_airdibayar.getText())
                        * Integer.parseInt(text_hargaSatuan.getText());

                if (TransaksiKontrol.getKoneksi().jual_selectTransaksiCek(label_noTrans.getText()) == true) {
                    label_status.setText("STATUS : LUNAS");
                    double dend = 0;
                    total = total + dend;
                } else { //kalo belum bayar
                    int index = combo_bulan.getSelectedIndex();//ambil bulan 
                    if (index == 0) {
                        index = 11;
                    } else {
                        index = index - 1;
                    }

                    String bulanSebelum = combo_bulan.getSelectedObjects()[index].toString();//bulan sblm bln skrg
                    if (bulan.equals(bulanSebelum) && Integer.parseInt(Tanggal.getTanggal2().split("-")[2]) > 10) {//kalo denda 
                        label_status.setText("STATUS : BLM LUNAS");
                        JOptionPane.showMessageDialog(null, "Denda Nih");

                        double dend = total * (2 / 100);
                        text_denda.setText(Double.toString(dend).split("\\.")[0]);
                        total = total + dend;
                        text_total.setText(Double.toString(total).split("\\.")[0]);
                    } else {//kalo gak denda
                        double dend = 0;
                        text_denda.setText(Double.toString(dend).split("\\.")[0]);
                        total = total + dend;
                        text_total.setText(Double.toString(total).split("\\.")[0]);
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormTransaksiPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_combo_bulanActionPerformed

    public void update() {
        try {
            List<Transaksi> agt = TransaksiKontrol.getKoneksi().jual_selectTransaksi();
            TransaksiJualTM model = new TransaksiJualTM(agt);
            tabel_penjualan.setModel(model);

            TableCellRenderer kanan = new RataKanan();
            tabel_penjualan.getColumnModel().getColumn(2).setCellRenderer(kanan);
            tabel_penjualan.getColumnModel().getColumn(3).setCellRenderer(kanan);
            tabel_penjualan.getColumnModel().getColumn(4).setCellRenderer(kanan);

            text_ttltransbeli.setText(TransaksiKontrol.getKoneksi().jual_tampilTotalBeliHariIni());
//        tabelDosen.getColumnModel().getColumn(0).setMinWidth(70);
//        tabelDosen.getColumnModel().getColumn(0).setMaxWidth(70);
//        tabelDosen.getColumnModel().getColumn(1).setMinWidth(220);
//        tabelDosen.getColumnModel().getColumn(1).setMaxWidth(220);
//            tabelDosen.setDefaultRenderer(Object.class, new renderWarnaWarni(Color.lightGray, Color.white));
        } catch (SQLException ex) {
            Logger.getLogger(FormAnggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void update2(String tanggal) {
        try {
            List<Transaksi> agt = TransaksiKontrol.getKoneksi().jual_selectTransaksiAll(tanggal);
            TransaksiJualAllTM model = new TransaksiJualAllTM(agt);
            tabel_penjualan2.setModel(model);

            TableCellRenderer kanan = new RataKanan();
            tabel_penjualan2.getColumnModel().getColumn(3).setCellRenderer(kanan);
            tabel_penjualan2.getColumnModel().getColumn(4).setCellRenderer(kanan);
            tabel_penjualan2.getColumnModel().getColumn(5).setCellRenderer(kanan);

            text_ttlbeliall.setText(TransaksiKontrol.getKoneksi().jual_tampilTotalBeliAll());
//        tabelDosen.getColumnModel().getColumn(0).setMinWidth(70);
//        tabelDosen.getColumnModel().getColumn(0).setMaxWidth(70);
//        tabelDosen.getColumnModel().getColumn(1).setMinWidth(220);
//        tabelDosen.getColumnModel().getColumn(1).setMaxWidth(220);
//            tabelDosen.setDefaultRenderer(Object.class, new renderWarnaWarni(Color.lightGray, Color.white));
        } catch (SQLException ex) {
            Logger.getLogger(FormAnggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public String konversiBulan(String bulan) {
        if (bulan.equals("JANUARI")) {
            return "01";
        } else if (bulan.equals("FEBRUARI")) {
            return "02";
        } else if (bulan.equals("MARET")) {
            return "03";
        } else if (bulan.equals("APRIL")) {
            return "04";
        } else if (bulan.equals("MEI")) {
            return "05";
        } else if (bulan.equals("JUNI")) {
            return "06";
        } else if (bulan.equals("JULI")) {
            return "07";
        } else if (bulan.equals("AGUSTUS")) {
            return "08";
        } else if (bulan.equals("SEPTEMBER")) {
            return "09";
        } else if (bulan.equals("OKTOBER")) {
            return "10";
        } else if (bulan.equals("NOVEMBER")) {
            return "11";
        } else if (bulan.equals("DESEMBER")) {
            return "12";
        } else {
            return "-";
        }
    }

    public void defaultnya() {
        button_tambah.setEnabled(true);
        button_ubah.setEnabled(false);
        button_hapus.setEnabled(false);
        text_noPelanggan.setText("");
        text_nama.setText("");
        text_airawal.setText("0");
        text_airdibayar.setText("0");
        text_hargaSatuan.setText("0");
        text_airbln.setText("0");
        text_total.setText("0");
        text_pembayaran.setText("0");
        text_noPelanggan.setEditable(true);
        label_noTrans.setVisible(false);
    }

    public void customnya() {
        button_tambah.setEnabled(false);
        button_ubah.setEnabled(true);
        button_hapus.setEnabled(true);
        text_noPelanggan.setEditable(false);
    }

    public void update(String key) {
        try {
            List<Anggota> agt = AnggotaKontrol.getKoneksi().selectAnggota2(key);
            AnggotaTM model = new AnggotaTM(agt);
            tabel_pelanggan.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(FormPemakaianAir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public String generateBulanTahun(String tanggal) {
        if (tanggal.split("-")[1].equals("01")) {
            return "JANUARI-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("02")) {
            return "FEBRUARI-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("03")) {
            return "MARET-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("04")) {
            return "APRIL-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("05")) {
            return "MEI-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("06")) {
            return "JUNI-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("07")) {
            return "JULI-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("08")) {
            return "AGUSTUS-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("09")) {
            return "SEPTEMBER-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("10")) {
            return "OKTOBER-" + tanggal.split("-")[0];
        } else if (tanggal.split("-")[1].equals("11")) {
            return "NOVEMBER-" + tanggal.split("-")[0];
        } else {
            return "DESEMBER-" + tanggal.split("-")[0];
        }
    }

    public String generateBulanTahun2(String bulan) {//bulan sekarang
        if (bulan.equals("JANUARI")) {
            return "02";
        } else if (bulan.equals("FEBRUARI")) {
            return "03";
        } else if (bulan.equals("MARET")) {
            return "04";
        } else if (bulan.equals("APRIL")) {
            return "05";
        } else if (bulan.equals("MEI")) {
            return "06";
        } else if (bulan.equals("JUNI")) {
            return "07";
        } else if (bulan.equals("JULI")) {
            return "08";
        } else if (bulan.equals("AGUSTUS")) {
            return "09";
        } else if (bulan.equals("SEPTEMBER")) {
            return "10";
        } else if (bulan.equals("OKTOBER")) {
            return "11";
        } else if (bulan.equals("NOVEMBER")) {
            return "12";
        } else {
            return "01";
        }
    }

    public String generateBulanTahun3(String bulan) {
        if (bulan.equals("01")) {
            return "JANUARI";
        } else if (bulan.equals("02")) {
            return "FEBRUARI";
        } else if (bulan.equals("03")) {
            return "MARET";
        } else if (bulan.equals("04")) {
            return "APRIL";
        } else if (bulan.equals("05")) {
            return "MEI";
        } else if (bulan.equals("06")) {
            return "JUNI";
        } else if (bulan.equals("07")) {
            return "JULI";
        } else if (bulan.equals("08")) {
            return "AGUSTUS";
        } else if (bulan.equals("09")) {
            return "SEPTEMBER";
        } else if (bulan.equals("10")) {
            return "OKTOBER";
        } else if (bulan.equals("11")) {
            return "NOVEMBER";
        } else if (bulan.equals("12")) {
            return "DESEMBER";
        } else if (bulan.equals("JANUARI")) {
            return "01";
        } else if (bulan.equals("FEBRUARI")) {
            return "02";
        } else if (bulan.equals("MARET")) {
            return "03";
        } else if (bulan.equals("APRIL")) {
            return "04";
        } else if (bulan.equals("MEI")) {
            return "05";
        } else if (bulan.equals("JUNI")) {
            return "06";
        } else if (bulan.equals("JULI")) {
            return "07";
        } else if (bulan.equals("AGUSTUS")) {
            return "08";
        } else if (bulan.equals("SEPTEMBER")) {
            return "09";
        } else if (bulan.equals("OKTOBER")) {
            return "10";
        } else if (bulan.equals("NOVEMBER")) {
            return "11";
        } else {
            return "12";
        }
    }

    public String generateKodeBaru(String kode) {
        int noTa = Integer.parseInt(kode.split("-")[1]);
        noTa = noTa + 1;
        System.out.println(kode.split("-")[0] + "-" + noTa);
        return kode.split("-")[0] + "-" + noTa;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksiPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_hapus;
    private javax.swing.JButton button_pelanggan;
    private javax.swing.JButton button_tabel;
    private javax.swing.JButton button_tambah;
    private javax.swing.JButton button_ubah;
    private javax.swing.JComboBox cb_bulan;
    private javax.swing.JComboBox cb_tahun;
    private javax.swing.JComboBox cb_tanggal;
    private javax.swing.JComboBox combo_bulan;
    private javax.swing.JDialog dialog_cariP;
    private javax.swing.JDialog dialog_pembelian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_alamatNotelp;
    private javax.swing.JLabel label_jmlBeli;
    private javax.swing.JLabel label_namaDesa;
    private javax.swing.JLabel label_noTrans;
    private javax.swing.JLabel label_status;
    private javax.swing.JLabel label_tanggal;
    private javax.swing.JTable tabel_pelanggan;
    private javax.swing.JTable tabel_penjualan;
    private javax.swing.JTable tabel_penjualan2;
    private javax.swing.JTextField text_airawal;
    private javax.swing.JTextField text_airbln;
    private javax.swing.JTextField text_airdibayar;
    private javax.swing.JTextField text_denda;
    private javax.swing.JTextField text_hargaSatuan;
    private javax.swing.JTextField text_key;
    private javax.swing.JTextField text_nama;
    private javax.swing.JTextField text_noPelanggan;
    private javax.swing.JTextField text_pembayaran;
    private javax.swing.JTextField text_total;
    private javax.swing.JTextField text_ttlbeliall;
    private javax.swing.JTextField text_ttltransbeli;
    // End of variables declaration//GEN-END:variables
}
