/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tambah_Anggota.java
 *
 * Created on May 8, 2014, 9:46:13 PM
 */
package Perdagangan;

import Perdagangan.Kontrol.Anggota;
import Perdagangan.Kontrol.Barang;
import Perdagangan.TabelModel.Tabel_Model_Anggota;
import Perdagangan.TabelModel.Tabel_Model_Barang;
import bumdes.*;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author Rafael Aweng
 */
public class Per_Anggota extends javax.swing.JFrame {

    String file = "../gambar/bg.jpg";

    /**
     * Creates new form Tambah_Anggota
     */
    public Per_Anggota() {
        try {
            initComponents();
            this.setLocationRelativeTo(null);

            updateTabel();
        } catch (Exception ex) {
            Logger.getLogger(Per_Anggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Per_Anggota(String pembeli) {
        try {
            initComponents();
            this.setLocationRelativeTo(null);

            tombolKembali.setText("BALIK");
            updateTabel();
        } catch (Exception ex) {
            Logger.getLogger(Per_Anggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        tombolKembali = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        isian_noAnggota = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        isian_namaAnggota = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        tombolTambah = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        tombolBatal = new javax.swing.JButton();
        tombolRubah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        isian_alamat = new javax.swing.JTextArea();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAnggota = new javax.swing.JTable();
        jPanel19 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRANSAKSI SIMPAN & PINJAM");

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMASI ANGGOTA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Times New Roman", 3, 24))); // NOI18N

        jPanel10.setBackground(new java.awt.Color(204, 204, 0));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tombolKembali.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tombolKembali.setText("KEMBALI");
        tombolKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tombolKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tombolKembali, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(204, 204, 0));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DETIL ANGGOTA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel20.setText("Kode Anggota");

        jLabel52.setText("Nama Anggota");

        jLabel53.setText("Alamat");

        tombolTambah.setText("TAMBAH");
        tombolTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahActionPerformed(evt);
            }
        });

        tombolHapus.setText("HAPUS");
        tombolHapus.setEnabled(false);
        tombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusActionPerformed(evt);
            }
        });

        tombolBatal.setText("BATAL");
        tombolBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolBatalActionPerformed(evt);
            }
        });

        tombolRubah.setText("RUBAH");
        tombolRubah.setEnabled(false);
        tombolRubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolRubahActionPerformed(evt);
            }
        });

        isian_alamat.setColumns(20);
        isian_alamat.setRows(5);
        jScrollPane2.setViewportView(isian_alamat);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addComponent(jLabel53)
                    .addComponent(jLabel20))
                .addGap(20, 20, 20)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(isian_noAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isian_namaAnggota)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tombolTambah)
                .addGap(7, 7, 7)
                .addComponent(tombolRubah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombolHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombolBatal)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(isian_noAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(isian_namaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel53)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolRubah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(204, 204, 0));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TABEL ANGGOTA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        tabelAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelAnggota);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel19.setBackground(new java.awt.Color(204, 204, 0));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA TRANSAKSI", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKembaliActionPerformed
        // TODO add your handling code here:
        if (tombolKembali.getText().equals("KEMBALI")) {
            new Perdagangan_Home().setVisible(true);
            this.setVisible(false);
        }
        else{
            this.setVisible(false);
            tombolKembali.setText("KEMBALI");
        }
    }//GEN-LAST:event_tombolKembaliActionPerformed

    private void tabelAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAnggotaMouseClicked
        int row1 = tabelAnggota.getSelectedRow();
        isian_noAnggota.setText(tabelAnggota.getValueAt(row1, 0).toString());//0 kolom pertama
        isian_namaAnggota.setText(tabelAnggota.getValueAt(row1, 1).toString());
        isian_alamat.setText(tabelAnggota.getValueAt(row1, 2).toString());
        tombolRubah.setEnabled(true);
        tombolHapus.setEnabled(true);
        isian_noAnggota.setEditable(false);
    }//GEN-LAST:event_tabelAnggotaMouseClicked

    private void tombolRubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolRubahActionPerformed
        try {
            Anggota agt = new Anggota();
            agt.noAnggota = isian_noAnggota.getText();
            agt.setNamaAnggota(isian_namaAnggota.getText());
            agt.setAlamat(isian_alamat.getText());
            agt.statusTerakhir = "TDK ADA TRANSAKSI";
            Perdagangan.Kontrol.Anggota_Kontrol.getKoneksi().updateAnggota(agt);
            JOptionPane.showMessageDialog(rootPane, "Pengubahan Member Sukses");
            updateTabel();
            bersihkan();
        } catch (SQLException ex) {
            Logger.getLogger(Per_Anggota.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Per_Anggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tombolRubahActionPerformed

    private void tombolBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBatalActionPerformed
        bersihkan();
    }//GEN-LAST:event_tombolBatalActionPerformed

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        int jwb = JOptionPane.showConfirmDialog(rootPane, "Yakin Hapus?");//O yes, 1 No, 2 Cancel
        if (jwb == 0) {
            try {
                Anggota agt = new Anggota();
                agt.noAnggota = isian_noAnggota.getText();
                Perdagangan.Kontrol.Anggota_Kontrol.getKoneksi().deleteAnggota(agt.noAnggota);
                JOptionPane.showMessageDialog(rootPane, "Penghapusan Member Sukses");
                updateTabel();
                bersihkan();
            } catch (SQLException ex) {
                Logger.getLogger(Per_Anggota.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(Per_Anggota.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void tombolTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTambahActionPerformed
        try {
            Anggota agt = new Anggota();
            agt.noAnggota = isian_noAnggota.getText();
            agt.setNamaAnggota(isian_namaAnggota.getText());
            agt.setAlamat(isian_alamat.getText());
            agt.statusTerakhir = "TDK ADA TRANSAKSI";
            Perdagangan.Kontrol.Anggota_Kontrol.getKoneksi().insertAnggota(agt);
            JOptionPane.showMessageDialog(rootPane, "Pengisian Member Sukses");
            updateTabel();
            bersihkan();
        } catch (SQLException ex) {
            Logger.getLogger(Per_Anggota.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Per_Anggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tombolTambahActionPerformed
//    public static String bulan(int b) {
//        String bb = "";
//        if (b == 1) {
//            bb = "JAN";
//        } else if (b == 2) {
//            bb = "FEB";
//        } else if (b == 3) {
//            bb = "MAR";
//        } else if (b == 4) {
//            bb = "APR";
//        } else if (b == 5) {
//            bb = "MAY";
//        } else if (b == 6) {
//            bb = "JUN";
//        } else if (b == 7) {
//            bb = "JUL";
//        } else if (b == 8) {
//            bb = "AUG";
//        } else if (b == 9) {
//            bb = "SEP";
//        } else if (b == 10) {
//            bb = "OKT";
//        } else if (b == 11) {
//            bb = "NOV";
//        } else if (b == 12) {
//            bb = "DEC";
//        }
//        return bb;
//    }

    public void tampilSimpanan(String nik) throws Exception {
//        List<Simpanan> a = Kontrol_Simpanan.getKoneksi().getAllSimpanan(nik);
//        Tabel_Model_Daftar_Simpanan model = new Tabel_Model_Daftar_Simpanan(a);
//        tabel_Daftar_Simpanan.setModel(model);
    }

    public void tampilPinjaman(String nik) throws Exception {
//        List<Pinjaman> a = Kontrol_Pinjaman.getKoneksi().getAllPinjaman(nik);
//        Tabel_Model_Daftar_Pinjaman model = new Tabel_Model_Daftar_Pinjaman(a);
//        tabel_Daftar_Pinjaman.setModel(model);
    }

    public void STATUSPinjaman(String nik) throws Exception {
//        List<Pinjaman> a = Kontrol_Pinjaman.getKoneksi().getAllPinjaman(nik);
//        double p = 0;
//        for (int i = 0; i < a.size(); i++) {
//            p += (a.get(i).getSaldo_Pokok_pinjaman() + a.get(i).getSaldo_Bunga());
//        }
//        if (p > 0) {
//            label_status_pinjam.setText(": Pinjam");
//        }
    }

    public void updateTabel() throws Exception {
        List<Anggota> a = Perdagangan.Kontrol.Anggota_Kontrol.getKoneksi().tampilAllAnggota();
        Tabel_Model_Anggota model = new Tabel_Model_Anggota(a);
        tabelAnggota.setModel(model);
    }

    public void bersihkan() {
        isian_noAnggota.setText("");
        isian_namaAnggota.setText("");
        isian_alamat.setText("");
        tombolRubah.setEnabled(false);
        tombolHapus.setEnabled(false);
        isian_noAnggota.setEditable(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
            java.awt.EventQueue.invokeLater(new Runnable() {

                public void run() {
                    new Per_Anggota().setVisible(true);
                }
            });
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea isian_alamat;
    private javax.swing.JTextField isian_namaAnggota;
    private javax.swing.JTextField isian_noAnggota;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelAnggota;
    private javax.swing.JButton tombolBatal;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolKembali;
    private javax.swing.JButton tombolRubah;
    private javax.swing.JButton tombolTambah;
    // End of variables declaration//GEN-END:variables
}
